-- Heritage V2 Foundation Migration 000001 (Down)

DROP TABLE IF EXISTS legacy_record_maps CASCADE;
DROP TABLE IF EXISTS idempotency_records CASCADE;
DROP TABLE IF EXISTS consumer_receipts CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;
DROP TABLE IF EXISTS audit_events CASCADE;
DROP FUNCTION IF EXISTS trg_audit_events_immutable CASCADE;

DROP TABLE IF EXISTS delegations CASCADE;
DROP TABLE IF EXISTS baseline_grants CASCADE;
DROP TABLE IF EXISTS scoped_grants CASCADE;
DROP TABLE IF EXISTS assignments CASCADE;
DROP TABLE IF EXISTS role_capabilities CASCADE;
DROP TABLE IF EXISTS capabilities CASCADE;
DROP TABLE IF EXISTS role_templates CASCADE;

DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS auth_methods CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

DROP TABLE IF EXISTS church_affiliations CASCADE;
DROP TABLE IF EXISTS contact_points CASCADE;
DROP TABLE IF EXISTS people CASCADE;

DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS sectors CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
