// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/cohortenrollment"
)

// CohortEnrollment is the model entity for the CohortEnrollment schema.
type CohortEnrollment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CohortID holds the value of the "cohort_id" field.
	CohortID uuid.UUID `json:"cohort_id,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID uuid.UUID `json:"member_id,omitempty"`
	// TeacherID holds the value of the "teacher_id" field.
	TeacherID *uuid.UUID `json:"teacher_id,omitempty"`
	// Status holds the value of the "status" field.
	Status cohortenrollment.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CohortEnrollment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cohortenrollment.FieldTeacherID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case cohortenrollment.FieldStatus:
			values[i] = new(sql.NullString)
		case cohortenrollment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case cohortenrollment.FieldID, cohortenrollment.FieldCohortID, cohortenrollment.FieldMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CohortEnrollment fields.
func (_m *CohortEnrollment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cohortenrollment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case cohortenrollment.FieldCohortID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field cohort_id", values[i])
			} else if value != nil {
				_m.CohortID = *value
			}
		case cohortenrollment.FieldMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value != nil {
				_m.MemberID = *value
			}
		case cohortenrollment.FieldTeacherID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field teacher_id", values[i])
			} else if value.Valid {
				_m.TeacherID = new(uuid.UUID)
				*_m.TeacherID = *value.S.(*uuid.UUID)
			}
		case cohortenrollment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = cohortenrollment.Status(value.String)
			}
		case cohortenrollment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CohortEnrollment.
// This includes values selected through modifiers, order, etc.
func (_m *CohortEnrollment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CohortEnrollment.
// Note that you need to call CohortEnrollment.Unwrap() before calling this method if this CohortEnrollment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CohortEnrollment) Update() *CohortEnrollmentUpdateOne {
	return NewCohortEnrollmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CohortEnrollment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CohortEnrollment) Unwrap() *CohortEnrollment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CohortEnrollment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CohortEnrollment) String() string {
	var builder strings.Builder
	builder.WriteString("CohortEnrollment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cohort_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CohortID))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberID))
	builder.WriteString(", ")
	if v := _m.TeacherID; v != nil {
		builder.WriteString("teacher_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CohortEnrollments is a parsable slice of CohortEnrollment.
type CohortEnrollments []*CohortEnrollment
