// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/hofchurchng/church-backend/internal/ent/featureflag"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
)

// FeatureFlagUpdate is the builder for updating FeatureFlag entities.
type FeatureFlagUpdate struct {
	config
	hooks    []Hook
	mutation *FeatureFlagMutation
}

// Where appends a list predicates to the FeatureFlagUpdate builder.
func (_u *FeatureFlagUpdate) Where(ps ...predicate.FeatureFlag) *FeatureFlagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *FeatureFlagUpdate) SetKey(v string) *FeatureFlagUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableKey(v *string) *FeatureFlagUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FeatureFlagUpdate) SetName(v string) *FeatureFlagUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableName(v *string) *FeatureFlagUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeatureFlagUpdate) SetDescription(v string) *FeatureFlagUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableDescription(v *string) *FeatureFlagUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeatureFlagUpdate) ClearDescription() *FeatureFlagUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *FeatureFlagUpdate) SetCategory(v string) *FeatureFlagUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableCategory(v *string) *FeatureFlagUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *FeatureFlagUpdate) SetIsEnabled(v bool) *FeatureFlagUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableIsEnabled(v *bool) *FeatureFlagUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetAllowedRoles sets the "allowed_roles" field.
func (_u *FeatureFlagUpdate) SetAllowedRoles(v []string) *FeatureFlagUpdate {
	_u.mutation.SetAllowedRoles(v)
	return _u
}

// AppendAllowedRoles appends value to the "allowed_roles" field.
func (_u *FeatureFlagUpdate) AppendAllowedRoles(v []string) *FeatureFlagUpdate {
	_u.mutation.AppendAllowedRoles(v)
	return _u
}

// ClearAllowedRoles clears the value of the "allowed_roles" field.
func (_u *FeatureFlagUpdate) ClearAllowedRoles() *FeatureFlagUpdate {
	_u.mutation.ClearAllowedRoles()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FeatureFlagUpdate) SetUpdatedBy(v string) *FeatureFlagUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableUpdatedBy(v *string) *FeatureFlagUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FeatureFlagUpdate) ClearUpdatedBy() *FeatureFlagUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FeatureFlagUpdate) SetCreatedAt(v time.Time) *FeatureFlagUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FeatureFlagUpdate) SetNillableCreatedAt(v *time.Time) *FeatureFlagUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureFlagUpdate) SetUpdatedAt(v time.Time) *FeatureFlagUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FeatureFlagMutation object of the builder.
func (_u *FeatureFlagUpdate) Mutation() *FeatureFlagMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeatureFlagUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureFlagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeatureFlagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureFlagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeatureFlagUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := featureflag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureFlagUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := featureflag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := featureflag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.name": %w`, err)}
		}
	}
	return nil
}

func (_u *FeatureFlagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(featureflag.Table, featureflag.Columns, sqlgraph.NewFieldSpec(featureflag.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(featureflag.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(featureflag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(featureflag.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(featureflag.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(featureflag.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(featureflag.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowedRoles(); ok {
		_spec.SetField(featureflag.FieldAllowedRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, featureflag.FieldAllowedRoles, value)
		})
	}
	if _u.mutation.AllowedRolesCleared() {
		_spec.ClearField(featureflag.FieldAllowedRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(featureflag.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(featureflag.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(featureflag.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(featureflag.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{featureflag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeatureFlagUpdateOne is the builder for updating a single FeatureFlag entity.
type FeatureFlagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeatureFlagMutation
}

// SetKey sets the "key" field.
func (_u *FeatureFlagUpdateOne) SetKey(v string) *FeatureFlagUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableKey(v *string) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FeatureFlagUpdateOne) SetName(v string) *FeatureFlagUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableName(v *string) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeatureFlagUpdateOne) SetDescription(v string) *FeatureFlagUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableDescription(v *string) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeatureFlagUpdateOne) ClearDescription() *FeatureFlagUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCategory sets the "category" field.
func (_u *FeatureFlagUpdateOne) SetCategory(v string) *FeatureFlagUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableCategory(v *string) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *FeatureFlagUpdateOne) SetIsEnabled(v bool) *FeatureFlagUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableIsEnabled(v *bool) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetAllowedRoles sets the "allowed_roles" field.
func (_u *FeatureFlagUpdateOne) SetAllowedRoles(v []string) *FeatureFlagUpdateOne {
	_u.mutation.SetAllowedRoles(v)
	return _u
}

// AppendAllowedRoles appends value to the "allowed_roles" field.
func (_u *FeatureFlagUpdateOne) AppendAllowedRoles(v []string) *FeatureFlagUpdateOne {
	_u.mutation.AppendAllowedRoles(v)
	return _u
}

// ClearAllowedRoles clears the value of the "allowed_roles" field.
func (_u *FeatureFlagUpdateOne) ClearAllowedRoles() *FeatureFlagUpdateOne {
	_u.mutation.ClearAllowedRoles()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FeatureFlagUpdateOne) SetUpdatedBy(v string) *FeatureFlagUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableUpdatedBy(v *string) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FeatureFlagUpdateOne) ClearUpdatedBy() *FeatureFlagUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FeatureFlagUpdateOne) SetCreatedAt(v time.Time) *FeatureFlagUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FeatureFlagUpdateOne) SetNillableCreatedAt(v *time.Time) *FeatureFlagUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureFlagUpdateOne) SetUpdatedAt(v time.Time) *FeatureFlagUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FeatureFlagMutation object of the builder.
func (_u *FeatureFlagUpdateOne) Mutation() *FeatureFlagMutation {
	return _u.mutation
}

// Where appends a list predicates to the FeatureFlagUpdate builder.
func (_u *FeatureFlagUpdateOne) Where(ps ...predicate.FeatureFlag) *FeatureFlagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeatureFlagUpdateOne) Select(field string, fields ...string) *FeatureFlagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FeatureFlag entity.
func (_u *FeatureFlagUpdateOne) Save(ctx context.Context) (*FeatureFlag, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureFlagUpdateOne) SaveX(ctx context.Context) *FeatureFlag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeatureFlagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureFlagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeatureFlagUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := featureflag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureFlagUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := featureflag.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := featureflag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FeatureFlag.name": %w`, err)}
		}
	}
	return nil
}

func (_u *FeatureFlagUpdateOne) sqlSave(ctx context.Context) (_node *FeatureFlag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(featureflag.Table, featureflag.Columns, sqlgraph.NewFieldSpec(featureflag.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FeatureFlag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, featureflag.FieldID)
		for _, f := range fields {
			if !featureflag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != featureflag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(featureflag.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(featureflag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(featureflag.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(featureflag.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(featureflag.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(featureflag.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowedRoles(); ok {
		_spec.SetField(featureflag.FieldAllowedRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, featureflag.FieldAllowedRoles, value)
		})
	}
	if _u.mutation.AllowedRolesCleared() {
		_spec.ClearField(featureflag.FieldAllowedRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(featureflag.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(featureflag.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(featureflag.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(featureflag.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FeatureFlag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{featureflag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
