// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/guardianrelationship"
	"github.com/hofchurchng/church-backend/internal/ent/member"
)

// GuardianRelationship is the model entity for the GuardianRelationship schema.
type GuardianRelationship struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ChildMemberID holds the value of the "child_member_id" field.
	ChildMemberID uuid.UUID `json:"child_member_id,omitempty"`
	// GuardianMemberID holds the value of the "guardian_member_id" field.
	GuardianMemberID uuid.UUID `json:"guardian_member_id,omitempty"`
	// Relationship holds the value of the "relationship" field.
	Relationship guardianrelationship.Relationship `json:"relationship,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GuardianRelationshipQuery when eager-loading is set.
	Edges        GuardianRelationshipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GuardianRelationshipEdges holds the relations/edges for other nodes in the graph.
type GuardianRelationshipEdges struct {
	// Child holds the value of the child edge.
	Child *Member `json:"child,omitempty"`
	// Guardian holds the value of the guardian edge.
	Guardian *Member `json:"guardian,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GuardianRelationshipEdges) ChildOrErr() (*Member, error) {
	if e.Child != nil {
		return e.Child, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: member.Label}
	}
	return nil, &NotLoadedError{edge: "child"}
}

// GuardianOrErr returns the Guardian value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GuardianRelationshipEdges) GuardianOrErr() (*Member, error) {
	if e.Guardian != nil {
		return e.Guardian, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: member.Label}
	}
	return nil, &NotLoadedError{edge: "guardian"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GuardianRelationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case guardianrelationship.FieldRelationship:
			values[i] = new(sql.NullString)
		case guardianrelationship.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case guardianrelationship.FieldID, guardianrelationship.FieldChildMemberID, guardianrelationship.FieldGuardianMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GuardianRelationship fields.
func (_m *GuardianRelationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case guardianrelationship.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case guardianrelationship.FieldChildMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field child_member_id", values[i])
			} else if value != nil {
				_m.ChildMemberID = *value
			}
		case guardianrelationship.FieldGuardianMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field guardian_member_id", values[i])
			} else if value != nil {
				_m.GuardianMemberID = *value
			}
		case guardianrelationship.FieldRelationship:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relationship", values[i])
			} else if value.Valid {
				_m.Relationship = guardianrelationship.Relationship(value.String)
			}
		case guardianrelationship.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GuardianRelationship.
// This includes values selected through modifiers, order, etc.
func (_m *GuardianRelationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChild queries the "child" edge of the GuardianRelationship entity.
func (_m *GuardianRelationship) QueryChild() *MemberQuery {
	return NewGuardianRelationshipClient(_m.config).QueryChild(_m)
}

// QueryGuardian queries the "guardian" edge of the GuardianRelationship entity.
func (_m *GuardianRelationship) QueryGuardian() *MemberQuery {
	return NewGuardianRelationshipClient(_m.config).QueryGuardian(_m)
}

// Update returns a builder for updating this GuardianRelationship.
// Note that you need to call GuardianRelationship.Unwrap() before calling this method if this GuardianRelationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GuardianRelationship) Update() *GuardianRelationshipUpdateOne {
	return NewGuardianRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GuardianRelationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GuardianRelationship) Unwrap() *GuardianRelationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GuardianRelationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GuardianRelationship) String() string {
	var builder strings.Builder
	builder.WriteString("GuardianRelationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("child_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildMemberID))
	builder.WriteString(", ")
	builder.WriteString("guardian_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GuardianMemberID))
	builder.WriteString(", ")
	builder.WriteString("relationship=")
	builder.WriteString(fmt.Sprintf("%v", _m.Relationship))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GuardianRelationships is a parsable slice of GuardianRelationship.
type GuardianRelationships []*GuardianRelationship
