// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/memberlandmark"
)

// MemberLandmark is the model entity for the MemberLandmark schema.
type MemberLandmark struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ChurchID holds the value of the "church_id" field.
	ChurchID uuid.UUID `json:"church_id,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID uuid.UUID `json:"member_id,omitempty"`
	// LandmarkType holds the value of the "landmark_type" field.
	LandmarkType memberlandmark.LandmarkType `json:"landmark_type,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// InstitutionOrOrg holds the value of the "institution_or_org" field.
	InstitutionOrOrg string `json:"institution_or_org,omitempty"`
	// EventDate holds the value of the "event_date" field.
	EventDate time.Time `json:"event_date,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID *uuid.UUID `json:"created_by_user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberLandmark) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberlandmark.FieldCreatedByUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case memberlandmark.FieldLandmarkType, memberlandmark.FieldTitle, memberlandmark.FieldInstitutionOrOrg, memberlandmark.FieldNotes:
			values[i] = new(sql.NullString)
		case memberlandmark.FieldEventDate, memberlandmark.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case memberlandmark.FieldID, memberlandmark.FieldChurchID, memberlandmark.FieldMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberLandmark fields.
func (_m *MemberLandmark) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberlandmark.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case memberlandmark.FieldChurchID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field church_id", values[i])
			} else if value != nil {
				_m.ChurchID = *value
			}
		case memberlandmark.FieldMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value != nil {
				_m.MemberID = *value
			}
		case memberlandmark.FieldLandmarkType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field landmark_type", values[i])
			} else if value.Valid {
				_m.LandmarkType = memberlandmark.LandmarkType(value.String)
			}
		case memberlandmark.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case memberlandmark.FieldInstitutionOrOrg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field institution_or_org", values[i])
			} else if value.Valid {
				_m.InstitutionOrOrg = value.String
			}
		case memberlandmark.FieldEventDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_date", values[i])
			} else if value.Valid {
				_m.EventDate = value.Time
			}
		case memberlandmark.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case memberlandmark.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = new(uuid.UUID)
				*_m.CreatedByUserID = *value.S.(*uuid.UUID)
			}
		case memberlandmark.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberLandmark.
// This includes values selected through modifiers, order, etc.
func (_m *MemberLandmark) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MemberLandmark.
// Note that you need to call MemberLandmark.Unwrap() before calling this method if this MemberLandmark
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberLandmark) Update() *MemberLandmarkUpdateOne {
	return NewMemberLandmarkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberLandmark entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberLandmark) Unwrap() *MemberLandmark {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberLandmark is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberLandmark) String() string {
	var builder strings.Builder
	builder.WriteString("MemberLandmark(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("church_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChurchID))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberID))
	builder.WriteString(", ")
	builder.WriteString("landmark_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.LandmarkType))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("institution_or_org=")
	builder.WriteString(_m.InstitutionOrOrg)
	builder.WriteString(", ")
	builder.WriteString("event_date=")
	builder.WriteString(_m.EventDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	if v := _m.CreatedByUserID; v != nil {
		builder.WriteString("created_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MemberLandmarks is a parsable slice of MemberLandmark.
type MemberLandmarks []*MemberLandmark
