// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hofchurchng/church-backend/internal/ent/membertransfer"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
)

// MemberTransferDelete is the builder for deleting a MemberTransfer entity.
type MemberTransferDelete struct {
	config
	hooks    []Hook
	mutation *MemberTransferMutation
}

// Where appends a list predicates to the MemberTransferDelete builder.
func (_d *MemberTransferDelete) Where(ps ...predicate.MemberTransfer) *MemberTransferDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemberTransferDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberTransferDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemberTransferDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(membertransfer.Table, sqlgraph.NewFieldSpec(membertransfer.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemberTransferDeleteOne is the builder for deleting a single MemberTransfer entity.
type MemberTransferDeleteOne struct {
	_d *MemberTransferDelete
}

// Where appends a list predicates to the MemberTransferDelete builder.
func (_d *MemberTransferDeleteOne) Where(ps ...predicate.MemberTransfer) *MemberTransferDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemberTransferDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{membertransfer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberTransferDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
