// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/membertransfer"
)

// MemberTransferCreate is the builder for creating a MemberTransfer entity.
type MemberTransferCreate struct {
	config
	mutation *MemberTransferMutation
	hooks    []Hook
}

// SetMemberID sets the "member_id" field.
func (_c *MemberTransferCreate) SetMemberID(v uuid.UUID) *MemberTransferCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetOriginChurchID sets the "origin_church_id" field.
func (_c *MemberTransferCreate) SetOriginChurchID(v uuid.UUID) *MemberTransferCreate {
	_c.mutation.SetOriginChurchID(v)
	return _c
}

// SetDestinationChurchID sets the "destination_church_id" field.
func (_c *MemberTransferCreate) SetDestinationChurchID(v uuid.UUID) *MemberTransferCreate {
	_c.mutation.SetDestinationChurchID(v)
	return _c
}

// SetTransferReason sets the "transfer_reason" field.
func (_c *MemberTransferCreate) SetTransferReason(v string) *MemberTransferCreate {
	_c.mutation.SetTransferReason(v)
	return _c
}

// SetNillableTransferReason sets the "transfer_reason" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillableTransferReason(v *string) *MemberTransferCreate {
	if v != nil {
		_c.SetTransferReason(*v)
	}
	return _c
}

// SetPastoralRecommendation sets the "pastoral_recommendation" field.
func (_c *MemberTransferCreate) SetPastoralRecommendation(v string) *MemberTransferCreate {
	_c.mutation.SetPastoralRecommendation(v)
	return _c
}

// SetNillablePastoralRecommendation sets the "pastoral_recommendation" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillablePastoralRecommendation(v *string) *MemberTransferCreate {
	if v != nil {
		_c.SetPastoralRecommendation(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MemberTransferCreate) SetStatus(v membertransfer.Status) *MemberTransferCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillableStatus(v *membertransfer.Status) *MemberTransferCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInitiatedByUserID sets the "initiated_by_user_id" field.
func (_c *MemberTransferCreate) SetInitiatedByUserID(v uuid.UUID) *MemberTransferCreate {
	_c.mutation.SetInitiatedByUserID(v)
	return _c
}

// SetReviewedByUserID sets the "reviewed_by_user_id" field.
func (_c *MemberTransferCreate) SetReviewedByUserID(v uuid.UUID) *MemberTransferCreate {
	_c.mutation.SetReviewedByUserID(v)
	return _c
}

// SetNillableReviewedByUserID sets the "reviewed_by_user_id" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillableReviewedByUserID(v *uuid.UUID) *MemberTransferCreate {
	if v != nil {
		_c.SetReviewedByUserID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemberTransferCreate) SetCreatedAt(v time.Time) *MemberTransferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillableCreatedAt(v *time.Time) *MemberTransferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *MemberTransferCreate) SetReviewedAt(v time.Time) *MemberTransferCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillableReviewedAt(v *time.Time) *MemberTransferCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemberTransferCreate) SetID(v uuid.UUID) *MemberTransferCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MemberTransferCreate) SetNillableID(v *uuid.UUID) *MemberTransferCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MemberTransferMutation object of the builder.
func (_c *MemberTransferCreate) Mutation() *MemberTransferMutation {
	return _c.mutation
}

// Save creates the MemberTransfer in the database.
func (_c *MemberTransferCreate) Save(ctx context.Context) (*MemberTransfer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberTransferCreate) SaveX(ctx context.Context) *MemberTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberTransferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberTransferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberTransferCreate) defaults() {
	if _, ok := _c.mutation.TransferReason(); !ok {
		v := membertransfer.DefaultTransferReason
		_c.mutation.SetTransferReason(v)
	}
	if _, ok := _c.mutation.PastoralRecommendation(); !ok {
		v := membertransfer.DefaultPastoralRecommendation
		_c.mutation.SetPastoralRecommendation(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := membertransfer.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := membertransfer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := membertransfer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberTransferCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "MemberTransfer.member_id"`)}
	}
	if _, ok := _c.mutation.OriginChurchID(); !ok {
		return &ValidationError{Name: "origin_church_id", err: errors.New(`ent: missing required field "MemberTransfer.origin_church_id"`)}
	}
	if _, ok := _c.mutation.DestinationChurchID(); !ok {
		return &ValidationError{Name: "destination_church_id", err: errors.New(`ent: missing required field "MemberTransfer.destination_church_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MemberTransfer.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := membertransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MemberTransfer.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InitiatedByUserID(); !ok {
		return &ValidationError{Name: "initiated_by_user_id", err: errors.New(`ent: missing required field "MemberTransfer.initiated_by_user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MemberTransfer.created_at"`)}
	}
	return nil
}

func (_c *MemberTransferCreate) sqlSave(ctx context.Context) (*MemberTransfer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberTransferCreate) createSpec() (*MemberTransfer, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberTransfer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(membertransfer.Table, sqlgraph.NewFieldSpec(membertransfer.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MemberID(); ok {
		_spec.SetField(membertransfer.FieldMemberID, field.TypeUUID, value)
		_node.MemberID = value
	}
	if value, ok := _c.mutation.OriginChurchID(); ok {
		_spec.SetField(membertransfer.FieldOriginChurchID, field.TypeUUID, value)
		_node.OriginChurchID = value
	}
	if value, ok := _c.mutation.DestinationChurchID(); ok {
		_spec.SetField(membertransfer.FieldDestinationChurchID, field.TypeUUID, value)
		_node.DestinationChurchID = value
	}
	if value, ok := _c.mutation.TransferReason(); ok {
		_spec.SetField(membertransfer.FieldTransferReason, field.TypeString, value)
		_node.TransferReason = value
	}
	if value, ok := _c.mutation.PastoralRecommendation(); ok {
		_spec.SetField(membertransfer.FieldPastoralRecommendation, field.TypeString, value)
		_node.PastoralRecommendation = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(membertransfer.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InitiatedByUserID(); ok {
		_spec.SetField(membertransfer.FieldInitiatedByUserID, field.TypeUUID, value)
		_node.InitiatedByUserID = value
	}
	if value, ok := _c.mutation.ReviewedByUserID(); ok {
		_spec.SetField(membertransfer.FieldReviewedByUserID, field.TypeUUID, value)
		_node.ReviewedByUserID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(membertransfer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(membertransfer.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	return _node, _spec
}

// MemberTransferCreateBulk is the builder for creating many MemberTransfer entities in bulk.
type MemberTransferCreateBulk struct {
	config
	err      error
	builders []*MemberTransferCreate
}

// Save creates the MemberTransfer entities in the database.
func (_c *MemberTransferCreateBulk) Save(ctx context.Context) ([]*MemberTransfer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberTransfer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberTransferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberTransferCreateBulk) SaveX(ctx context.Context) []*MemberTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberTransferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberTransferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
