// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/outreachtargets"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/ent/user"
)

// OutreachTargetsUpdate is the builder for updating OutreachTargets entities.
type OutreachTargetsUpdate struct {
	config
	hooks    []Hook
	mutation *OutreachTargetsMutation
}

// Where appends a list predicates to the OutreachTargetsUpdate builder.
func (_u *OutreachTargetsUpdate) Where(ps ...predicate.OutreachTargets) *OutreachTargetsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerType sets the "owner_type" field.
func (_u *OutreachTargetsUpdate) SetOwnerType(v outreachtargets.OwnerType) *OutreachTargetsUpdate {
	_u.mutation.SetOwnerType(v)
	return _u
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_u *OutreachTargetsUpdate) SetNillableOwnerType(v *outreachtargets.OwnerType) *OutreachTargetsUpdate {
	if v != nil {
		_u.SetOwnerType(*v)
	}
	return _u
}

// ClearOwnerType clears the value of the "owner_type" field.
func (_u *OutreachTargetsUpdate) ClearOwnerType() *OutreachTargetsUpdate {
	_u.mutation.ClearOwnerType()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OutreachTargetsUpdate) SetUserID(v uuid.UUID) *OutreachTargetsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OutreachTargetsUpdate) SetNillableUserID(v *uuid.UUID) *OutreachTargetsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OutreachTargetsUpdate) ClearUserID() *OutreachTargetsUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetTargetCount sets the "target_count" field.
func (_u *OutreachTargetsUpdate) SetTargetCount(v int) *OutreachTargetsUpdate {
	_u.mutation.ResetTargetCount()
	_u.mutation.SetTargetCount(v)
	return _u
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_u *OutreachTargetsUpdate) SetNillableTargetCount(v *int) *OutreachTargetsUpdate {
	if v != nil {
		_u.SetTargetCount(*v)
	}
	return _u
}

// AddTargetCount adds value to the "target_count" field.
func (_u *OutreachTargetsUpdate) AddTargetCount(v int) *OutreachTargetsUpdate {
	_u.mutation.AddTargetCount(v)
	return _u
}

// SetPeriod sets the "period" field.
func (_u *OutreachTargetsUpdate) SetPeriod(v string) *OutreachTargetsUpdate {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *OutreachTargetsUpdate) SetNillablePeriod(v *string) *OutreachTargetsUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OutreachTargetsUpdate) SetCreatedAt(v time.Time) *OutreachTargetsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OutreachTargetsUpdate) SetNillableCreatedAt(v *time.Time) *OutreachTargetsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OutreachTargetsUpdate) SetUser(v *User) *OutreachTargetsUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OutreachTargetsMutation object of the builder.
func (_u *OutreachTargetsUpdate) Mutation() *OutreachTargetsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OutreachTargetsUpdate) ClearUser() *OutreachTargetsUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutreachTargetsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutreachTargetsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutreachTargetsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutreachTargetsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutreachTargetsUpdate) check() error {
	if v, ok := _u.mutation.OwnerType(); ok {
		if err := outreachtargets.OwnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "owner_type", err: fmt.Errorf(`ent: validator failed for field "OutreachTargets.owner_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OutreachTargetsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outreachtargets.Table, outreachtargets.Columns, sqlgraph.NewFieldSpec(outreachtargets.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerType(); ok {
		_spec.SetField(outreachtargets.FieldOwnerType, field.TypeEnum, value)
	}
	if _u.mutation.OwnerTypeCleared() {
		_spec.ClearField(outreachtargets.FieldOwnerType, field.TypeEnum)
	}
	if value, ok := _u.mutation.TargetCount(); ok {
		_spec.SetField(outreachtargets.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetCount(); ok {
		_spec.AddField(outreachtargets.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(outreachtargets.FieldPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(outreachtargets.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   outreachtargets.UserTable,
			Columns: []string{outreachtargets.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   outreachtargets.UserTable,
			Columns: []string{outreachtargets.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outreachtargets.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutreachTargetsUpdateOne is the builder for updating a single OutreachTargets entity.
type OutreachTargetsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutreachTargetsMutation
}

// SetOwnerType sets the "owner_type" field.
func (_u *OutreachTargetsUpdateOne) SetOwnerType(v outreachtargets.OwnerType) *OutreachTargetsUpdateOne {
	_u.mutation.SetOwnerType(v)
	return _u
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_u *OutreachTargetsUpdateOne) SetNillableOwnerType(v *outreachtargets.OwnerType) *OutreachTargetsUpdateOne {
	if v != nil {
		_u.SetOwnerType(*v)
	}
	return _u
}

// ClearOwnerType clears the value of the "owner_type" field.
func (_u *OutreachTargetsUpdateOne) ClearOwnerType() *OutreachTargetsUpdateOne {
	_u.mutation.ClearOwnerType()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OutreachTargetsUpdateOne) SetUserID(v uuid.UUID) *OutreachTargetsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OutreachTargetsUpdateOne) SetNillableUserID(v *uuid.UUID) *OutreachTargetsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *OutreachTargetsUpdateOne) ClearUserID() *OutreachTargetsUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetTargetCount sets the "target_count" field.
func (_u *OutreachTargetsUpdateOne) SetTargetCount(v int) *OutreachTargetsUpdateOne {
	_u.mutation.ResetTargetCount()
	_u.mutation.SetTargetCount(v)
	return _u
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_u *OutreachTargetsUpdateOne) SetNillableTargetCount(v *int) *OutreachTargetsUpdateOne {
	if v != nil {
		_u.SetTargetCount(*v)
	}
	return _u
}

// AddTargetCount adds value to the "target_count" field.
func (_u *OutreachTargetsUpdateOne) AddTargetCount(v int) *OutreachTargetsUpdateOne {
	_u.mutation.AddTargetCount(v)
	return _u
}

// SetPeriod sets the "period" field.
func (_u *OutreachTargetsUpdateOne) SetPeriod(v string) *OutreachTargetsUpdateOne {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *OutreachTargetsUpdateOne) SetNillablePeriod(v *string) *OutreachTargetsUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OutreachTargetsUpdateOne) SetCreatedAt(v time.Time) *OutreachTargetsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OutreachTargetsUpdateOne) SetNillableCreatedAt(v *time.Time) *OutreachTargetsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OutreachTargetsUpdateOne) SetUser(v *User) *OutreachTargetsUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OutreachTargetsMutation object of the builder.
func (_u *OutreachTargetsUpdateOne) Mutation() *OutreachTargetsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OutreachTargetsUpdateOne) ClearUser() *OutreachTargetsUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OutreachTargetsUpdate builder.
func (_u *OutreachTargetsUpdateOne) Where(ps ...predicate.OutreachTargets) *OutreachTargetsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutreachTargetsUpdateOne) Select(field string, fields ...string) *OutreachTargetsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutreachTargets entity.
func (_u *OutreachTargetsUpdateOne) Save(ctx context.Context) (*OutreachTargets, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutreachTargetsUpdateOne) SaveX(ctx context.Context) *OutreachTargets {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutreachTargetsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutreachTargetsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutreachTargetsUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerType(); ok {
		if err := outreachtargets.OwnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "owner_type", err: fmt.Errorf(`ent: validator failed for field "OutreachTargets.owner_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OutreachTargetsUpdateOne) sqlSave(ctx context.Context) (_node *OutreachTargets, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outreachtargets.Table, outreachtargets.Columns, sqlgraph.NewFieldSpec(outreachtargets.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutreachTargets.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outreachtargets.FieldID)
		for _, f := range fields {
			if !outreachtargets.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outreachtargets.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerType(); ok {
		_spec.SetField(outreachtargets.FieldOwnerType, field.TypeEnum, value)
	}
	if _u.mutation.OwnerTypeCleared() {
		_spec.ClearField(outreachtargets.FieldOwnerType, field.TypeEnum)
	}
	if value, ok := _u.mutation.TargetCount(); ok {
		_spec.SetField(outreachtargets.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetCount(); ok {
		_spec.AddField(outreachtargets.FieldTargetCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(outreachtargets.FieldPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(outreachtargets.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   outreachtargets.UserTable,
			Columns: []string{outreachtargets.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   outreachtargets.UserTable,
			Columns: []string{outreachtargets.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OutreachTargets{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outreachtargets.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
