// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/localchurch"
	"github.com/hofchurchng/church-backend/internal/ent/member"
	"github.com/hofchurchng/church-backend/internal/ent/otpinvites"
	"github.com/hofchurchng/church-backend/internal/ent/outreachreport"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/ent/sector"
	"github.com/hofchurchng/church-backend/internal/ent/soul"
	"github.com/hofchurchng/church-backend/internal/ent/team"
	"github.com/hofchurchng/church-backend/internal/ent/user"
	"github.com/hofchurchng/church-backend/internal/ent/usersector"
)

// SectorUpdate is the builder for updating Sector entities.
type SectorUpdate struct {
	config
	hooks    []Hook
	mutation *SectorMutation
}

// Where appends a list predicates to the SectorUpdate builder.
func (_u *SectorUpdate) Where(ps ...predicate.Sector) *SectorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChurchID sets the "church_id" field.
func (_u *SectorUpdate) SetChurchID(v uuid.UUID) *SectorUpdate {
	_u.mutation.SetChurchID(v)
	return _u
}

// SetNillableChurchID sets the "church_id" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableChurchID(v *uuid.UUID) *SectorUpdate {
	if v != nil {
		_u.SetChurchID(*v)
	}
	return _u
}

// ClearChurchID clears the value of the "church_id" field.
func (_u *SectorUpdate) ClearChurchID() *SectorUpdate {
	_u.mutation.ClearChurchID()
	return _u
}

// SetSectorName sets the "sector_name" field.
func (_u *SectorUpdate) SetSectorName(v string) *SectorUpdate {
	_u.mutation.SetSectorName(v)
	return _u
}

// SetNillableSectorName sets the "sector_name" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableSectorName(v *string) *SectorUpdate {
	if v != nil {
		_u.SetSectorName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SectorUpdate) SetDescription(v string) *SectorUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableDescription(v *string) *SectorUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SectorUpdate) ClearDescription() *SectorUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SectorUpdate) SetCreatedAt(v time.Time) *SectorUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableCreatedAt(v *time.Time) *SectorUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddMemberIDs adds the "members" edge to the Member entity by IDs.
func (_u *SectorUpdate) AddMemberIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the Member entity.
func (_u *SectorUpdate) AddMembers(v ...*Member) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// SetChurch sets the "church" edge to the LocalChurch entity.
func (_u *SectorUpdate) SetChurch(v *LocalChurch) *SectorUpdate {
	return _u.SetChurchID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *SectorUpdate) AddUserIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *SectorUpdate) AddUsers(v ...*User) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *SectorUpdate) AddTeamIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *SectorUpdate) AddTeams(v ...*Team) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddSoulIDs adds the "souls" edge to the Soul entity by IDs.
func (_u *SectorUpdate) AddSoulIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddSoulIDs(ids...)
	return _u
}

// AddSouls adds the "souls" edges to the Soul entity.
func (_u *SectorUpdate) AddSouls(v ...*Soul) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSoulIDs(ids...)
}

// AddOutreachReportIDs adds the "outreach_reports" edge to the OutreachReport entity by IDs.
func (_u *SectorUpdate) AddOutreachReportIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddOutreachReportIDs(ids...)
	return _u
}

// AddOutreachReports adds the "outreach_reports" edges to the OutreachReport entity.
func (_u *SectorUpdate) AddOutreachReports(v ...*OutreachReport) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutreachReportIDs(ids...)
}

// AddOtpInviteIDs adds the "otp_invites" edge to the OtpInvites entity by IDs.
func (_u *SectorUpdate) AddOtpInviteIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddOtpInviteIDs(ids...)
	return _u
}

// AddOtpInvites adds the "otp_invites" edges to the OtpInvites entity.
func (_u *SectorUpdate) AddOtpInvites(v ...*OtpInvites) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOtpInviteIDs(ids...)
}

// AddUserSectorIDs adds the "user_sectors" edge to the UserSector entity by IDs.
func (_u *SectorUpdate) AddUserSectorIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.AddUserSectorIDs(ids...)
	return _u
}

// AddUserSectors adds the "user_sectors" edges to the UserSector entity.
func (_u *SectorUpdate) AddUserSectors(v ...*UserSector) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSectorIDs(ids...)
}

// Mutation returns the SectorMutation object of the builder.
func (_u *SectorUpdate) Mutation() *SectorMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the Member entity.
func (_u *SectorUpdate) ClearMembers() *SectorUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to Member entities by IDs.
func (_u *SectorUpdate) RemoveMemberIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to Member entities.
func (_u *SectorUpdate) RemoveMembers(v ...*Member) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearChurch clears the "church" edge to the LocalChurch entity.
func (_u *SectorUpdate) ClearChurch() *SectorUpdate {
	_u.mutation.ClearChurch()
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *SectorUpdate) ClearUsers() *SectorUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *SectorUpdate) RemoveUserIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *SectorUpdate) RemoveUsers(v ...*User) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *SectorUpdate) ClearTeams() *SectorUpdate {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *SectorUpdate) RemoveTeamIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *SectorUpdate) RemoveTeams(v ...*Team) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearSouls clears all "souls" edges to the Soul entity.
func (_u *SectorUpdate) ClearSouls() *SectorUpdate {
	_u.mutation.ClearSouls()
	return _u
}

// RemoveSoulIDs removes the "souls" edge to Soul entities by IDs.
func (_u *SectorUpdate) RemoveSoulIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveSoulIDs(ids...)
	return _u
}

// RemoveSouls removes "souls" edges to Soul entities.
func (_u *SectorUpdate) RemoveSouls(v ...*Soul) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSoulIDs(ids...)
}

// ClearOutreachReports clears all "outreach_reports" edges to the OutreachReport entity.
func (_u *SectorUpdate) ClearOutreachReports() *SectorUpdate {
	_u.mutation.ClearOutreachReports()
	return _u
}

// RemoveOutreachReportIDs removes the "outreach_reports" edge to OutreachReport entities by IDs.
func (_u *SectorUpdate) RemoveOutreachReportIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveOutreachReportIDs(ids...)
	return _u
}

// RemoveOutreachReports removes "outreach_reports" edges to OutreachReport entities.
func (_u *SectorUpdate) RemoveOutreachReports(v ...*OutreachReport) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutreachReportIDs(ids...)
}

// ClearOtpInvites clears all "otp_invites" edges to the OtpInvites entity.
func (_u *SectorUpdate) ClearOtpInvites() *SectorUpdate {
	_u.mutation.ClearOtpInvites()
	return _u
}

// RemoveOtpInviteIDs removes the "otp_invites" edge to OtpInvites entities by IDs.
func (_u *SectorUpdate) RemoveOtpInviteIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveOtpInviteIDs(ids...)
	return _u
}

// RemoveOtpInvites removes "otp_invites" edges to OtpInvites entities.
func (_u *SectorUpdate) RemoveOtpInvites(v ...*OtpInvites) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOtpInviteIDs(ids...)
}

// ClearUserSectors clears all "user_sectors" edges to the UserSector entity.
func (_u *SectorUpdate) ClearUserSectors() *SectorUpdate {
	_u.mutation.ClearUserSectors()
	return _u
}

// RemoveUserSectorIDs removes the "user_sectors" edge to UserSector entities by IDs.
func (_u *SectorUpdate) RemoveUserSectorIDs(ids ...uuid.UUID) *SectorUpdate {
	_u.mutation.RemoveUserSectorIDs(ids...)
	return _u
}

// RemoveUserSectors removes "user_sectors" edges to UserSector entities.
func (_u *SectorUpdate) RemoveUserSectors(v ...*UserSector) *SectorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSectorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SectorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SectorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SectorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sector.Table, sector.Columns, sqlgraph.NewFieldSpec(sector.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SectorName(); ok {
		_spec.SetField(sector.FieldSectorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(sector.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(sector.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sector.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.MembersTable,
			Columns: []string{sector.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.MembersTable,
			Columns: []string{sector.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.MembersTable,
			Columns: []string{sector.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.ChurchTable,
			Columns: []string{sector.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.ChurchTable,
			Columns: []string{sector.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UsersTable,
			Columns: []string{sector.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UsersTable,
			Columns: []string{sector.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UsersTable,
			Columns: []string{sector.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.TeamsTable,
			Columns: []string{sector.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.TeamsTable,
			Columns: []string{sector.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.TeamsTable,
			Columns: []string{sector.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SoulsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.SoulsTable,
			Columns: []string{sector.SoulsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(soul.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSoulsIDs(); len(nodes) > 0 && !_u.mutation.SoulsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.SoulsTable,
			Columns: []string{sector.SoulsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(soul.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SoulsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.SoulsTable,
			Columns: []string{sector.SoulsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(soul.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutreachReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OutreachReportsTable,
			Columns: []string{sector.OutreachReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outreachreport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutreachReportsIDs(); len(nodes) > 0 && !_u.mutation.OutreachReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OutreachReportsTable,
			Columns: []string{sector.OutreachReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outreachreport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutreachReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OutreachReportsTable,
			Columns: []string{sector.OutreachReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outreachreport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OtpInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OtpInvitesTable,
			Columns: []string{sector.OtpInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(otpinvites.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOtpInvitesIDs(); len(nodes) > 0 && !_u.mutation.OtpInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OtpInvitesTable,
			Columns: []string{sector.OtpInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(otpinvites.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OtpInvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OtpInvitesTable,
			Columns: []string{sector.OtpInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(otpinvites.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserSectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UserSectorsTable,
			Columns: []string{sector.UserSectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersector.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSectorsIDs(); len(nodes) > 0 && !_u.mutation.UserSectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UserSectorsTable,
			Columns: []string{sector.UserSectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersector.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSectorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UserSectorsTable,
			Columns: []string{sector.UserSectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersector.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SectorUpdateOne is the builder for updating a single Sector entity.
type SectorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SectorMutation
}

// SetChurchID sets the "church_id" field.
func (_u *SectorUpdateOne) SetChurchID(v uuid.UUID) *SectorUpdateOne {
	_u.mutation.SetChurchID(v)
	return _u
}

// SetNillableChurchID sets the "church_id" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableChurchID(v *uuid.UUID) *SectorUpdateOne {
	if v != nil {
		_u.SetChurchID(*v)
	}
	return _u
}

// ClearChurchID clears the value of the "church_id" field.
func (_u *SectorUpdateOne) ClearChurchID() *SectorUpdateOne {
	_u.mutation.ClearChurchID()
	return _u
}

// SetSectorName sets the "sector_name" field.
func (_u *SectorUpdateOne) SetSectorName(v string) *SectorUpdateOne {
	_u.mutation.SetSectorName(v)
	return _u
}

// SetNillableSectorName sets the "sector_name" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableSectorName(v *string) *SectorUpdateOne {
	if v != nil {
		_u.SetSectorName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SectorUpdateOne) SetDescription(v string) *SectorUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableDescription(v *string) *SectorUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SectorUpdateOne) ClearDescription() *SectorUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SectorUpdateOne) SetCreatedAt(v time.Time) *SectorUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableCreatedAt(v *time.Time) *SectorUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddMemberIDs adds the "members" edge to the Member entity by IDs.
func (_u *SectorUpdateOne) AddMemberIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the Member entity.
func (_u *SectorUpdateOne) AddMembers(v ...*Member) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// SetChurch sets the "church" edge to the LocalChurch entity.
func (_u *SectorUpdateOne) SetChurch(v *LocalChurch) *SectorUpdateOne {
	return _u.SetChurchID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *SectorUpdateOne) AddUserIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *SectorUpdateOne) AddUsers(v ...*User) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *SectorUpdateOne) AddTeamIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *SectorUpdateOne) AddTeams(v ...*Team) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddSoulIDs adds the "souls" edge to the Soul entity by IDs.
func (_u *SectorUpdateOne) AddSoulIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddSoulIDs(ids...)
	return _u
}

// AddSouls adds the "souls" edges to the Soul entity.
func (_u *SectorUpdateOne) AddSouls(v ...*Soul) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSoulIDs(ids...)
}

// AddOutreachReportIDs adds the "outreach_reports" edge to the OutreachReport entity by IDs.
func (_u *SectorUpdateOne) AddOutreachReportIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddOutreachReportIDs(ids...)
	return _u
}

// AddOutreachReports adds the "outreach_reports" edges to the OutreachReport entity.
func (_u *SectorUpdateOne) AddOutreachReports(v ...*OutreachReport) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOutreachReportIDs(ids...)
}

// AddOtpInviteIDs adds the "otp_invites" edge to the OtpInvites entity by IDs.
func (_u *SectorUpdateOne) AddOtpInviteIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddOtpInviteIDs(ids...)
	return _u
}

// AddOtpInvites adds the "otp_invites" edges to the OtpInvites entity.
func (_u *SectorUpdateOne) AddOtpInvites(v ...*OtpInvites) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOtpInviteIDs(ids...)
}

// AddUserSectorIDs adds the "user_sectors" edge to the UserSector entity by IDs.
func (_u *SectorUpdateOne) AddUserSectorIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.AddUserSectorIDs(ids...)
	return _u
}

// AddUserSectors adds the "user_sectors" edges to the UserSector entity.
func (_u *SectorUpdateOne) AddUserSectors(v ...*UserSector) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSectorIDs(ids...)
}

// Mutation returns the SectorMutation object of the builder.
func (_u *SectorUpdateOne) Mutation() *SectorMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the Member entity.
func (_u *SectorUpdateOne) ClearMembers() *SectorUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to Member entities by IDs.
func (_u *SectorUpdateOne) RemoveMemberIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to Member entities.
func (_u *SectorUpdateOne) RemoveMembers(v ...*Member) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearChurch clears the "church" edge to the LocalChurch entity.
func (_u *SectorUpdateOne) ClearChurch() *SectorUpdateOne {
	_u.mutation.ClearChurch()
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *SectorUpdateOne) ClearUsers() *SectorUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *SectorUpdateOne) RemoveUserIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *SectorUpdateOne) RemoveUsers(v ...*User) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *SectorUpdateOne) ClearTeams() *SectorUpdateOne {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *SectorUpdateOne) RemoveTeamIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *SectorUpdateOne) RemoveTeams(v ...*Team) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearSouls clears all "souls" edges to the Soul entity.
func (_u *SectorUpdateOne) ClearSouls() *SectorUpdateOne {
	_u.mutation.ClearSouls()
	return _u
}

// RemoveSoulIDs removes the "souls" edge to Soul entities by IDs.
func (_u *SectorUpdateOne) RemoveSoulIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveSoulIDs(ids...)
	return _u
}

// RemoveSouls removes "souls" edges to Soul entities.
func (_u *SectorUpdateOne) RemoveSouls(v ...*Soul) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSoulIDs(ids...)
}

// ClearOutreachReports clears all "outreach_reports" edges to the OutreachReport entity.
func (_u *SectorUpdateOne) ClearOutreachReports() *SectorUpdateOne {
	_u.mutation.ClearOutreachReports()
	return _u
}

// RemoveOutreachReportIDs removes the "outreach_reports" edge to OutreachReport entities by IDs.
func (_u *SectorUpdateOne) RemoveOutreachReportIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveOutreachReportIDs(ids...)
	return _u
}

// RemoveOutreachReports removes "outreach_reports" edges to OutreachReport entities.
func (_u *SectorUpdateOne) RemoveOutreachReports(v ...*OutreachReport) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOutreachReportIDs(ids...)
}

// ClearOtpInvites clears all "otp_invites" edges to the OtpInvites entity.
func (_u *SectorUpdateOne) ClearOtpInvites() *SectorUpdateOne {
	_u.mutation.ClearOtpInvites()
	return _u
}

// RemoveOtpInviteIDs removes the "otp_invites" edge to OtpInvites entities by IDs.
func (_u *SectorUpdateOne) RemoveOtpInviteIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveOtpInviteIDs(ids...)
	return _u
}

// RemoveOtpInvites removes "otp_invites" edges to OtpInvites entities.
func (_u *SectorUpdateOne) RemoveOtpInvites(v ...*OtpInvites) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOtpInviteIDs(ids...)
}

// ClearUserSectors clears all "user_sectors" edges to the UserSector entity.
func (_u *SectorUpdateOne) ClearUserSectors() *SectorUpdateOne {
	_u.mutation.ClearUserSectors()
	return _u
}

// RemoveUserSectorIDs removes the "user_sectors" edge to UserSector entities by IDs.
func (_u *SectorUpdateOne) RemoveUserSectorIDs(ids ...uuid.UUID) *SectorUpdateOne {
	_u.mutation.RemoveUserSectorIDs(ids...)
	return _u
}

// RemoveUserSectors removes "user_sectors" edges to UserSector entities.
func (_u *SectorUpdateOne) RemoveUserSectors(v ...*UserSector) *SectorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSectorIDs(ids...)
}

// Where appends a list predicates to the SectorUpdate builder.
func (_u *SectorUpdateOne) Where(ps ...predicate.Sector) *SectorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SectorUpdateOne) Select(field string, fields ...string) *SectorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sector entity.
func (_u *SectorUpdateOne) Save(ctx context.Context) (*Sector, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectorUpdateOne) SaveX(ctx context.Context) *Sector {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SectorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SectorUpdateOne) sqlSave(ctx context.Context) (_node *Sector, err error) {
	_spec := sqlgraph.NewUpdateSpec(sector.Table, sector.Columns, sqlgraph.NewFieldSpec(sector.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sector.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sector.FieldID)
		for _, f := range fields {
			if !sector.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SectorName(); ok {
		_spec.SetField(sector.FieldSectorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(sector.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(sector.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sector.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.MembersTable,
			Columns: []string{sector.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.MembersTable,
			Columns: []string{sector.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.MembersTable,
			Columns: []string{sector.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.ChurchTable,
			Columns: []string{sector.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.ChurchTable,
			Columns: []string{sector.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UsersTable,
			Columns: []string{sector.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UsersTable,
			Columns: []string{sector.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UsersTable,
			Columns: []string{sector.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.TeamsTable,
			Columns: []string{sector.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.TeamsTable,
			Columns: []string{sector.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.TeamsTable,
			Columns: []string{sector.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SoulsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.SoulsTable,
			Columns: []string{sector.SoulsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(soul.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSoulsIDs(); len(nodes) > 0 && !_u.mutation.SoulsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.SoulsTable,
			Columns: []string{sector.SoulsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(soul.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SoulsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.SoulsTable,
			Columns: []string{sector.SoulsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(soul.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OutreachReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OutreachReportsTable,
			Columns: []string{sector.OutreachReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outreachreport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOutreachReportsIDs(); len(nodes) > 0 && !_u.mutation.OutreachReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OutreachReportsTable,
			Columns: []string{sector.OutreachReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outreachreport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OutreachReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OutreachReportsTable,
			Columns: []string{sector.OutreachReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outreachreport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OtpInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OtpInvitesTable,
			Columns: []string{sector.OtpInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(otpinvites.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOtpInvitesIDs(); len(nodes) > 0 && !_u.mutation.OtpInvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OtpInvitesTable,
			Columns: []string{sector.OtpInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(otpinvites.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OtpInvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.OtpInvitesTable,
			Columns: []string{sector.OtpInvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(otpinvites.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserSectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UserSectorsTable,
			Columns: []string{sector.UserSectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersector.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSectorsIDs(); len(nodes) > 0 && !_u.mutation.UserSectorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UserSectorsTable,
			Columns: []string{sector.UserSectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersector.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSectorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sector.UserSectorsTable,
			Columns: []string{sector.UserSectorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersector.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sector{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
