// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/ent/souljournal"
)

// SoulJournalDelete is the builder for deleting a SoulJournal entity.
type SoulJournalDelete struct {
	config
	hooks    []Hook
	mutation *SoulJournalMutation
}

// Where appends a list predicates to the SoulJournalDelete builder.
func (_d *SoulJournalDelete) Where(ps ...predicate.SoulJournal) *SoulJournalDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SoulJournalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoulJournalDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SoulJournalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(souljournal.Table, sqlgraph.NewFieldSpec(souljournal.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SoulJournalDeleteOne is the builder for deleting a single SoulJournal entity.
type SoulJournalDeleteOne struct {
	_d *SoulJournalDelete
}

// Where appends a list predicates to the SoulJournalDelete builder.
func (_d *SoulJournalDeleteOne) Where(ps ...predicate.SoulJournal) *SoulJournalDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SoulJournalDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{souljournal.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoulJournalDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
