// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/ent/team"
	"github.com/hofchurchng/church-backend/internal/ent/teamvolunteers"
	"github.com/hofchurchng/church-backend/internal/ent/user"
)

// TeamVolunteersUpdate is the builder for updating TeamVolunteers entities.
type TeamVolunteersUpdate struct {
	config
	hooks    []Hook
	mutation *TeamVolunteersMutation
}

// Where appends a list predicates to the TeamVolunteersUpdate builder.
func (_u *TeamVolunteersUpdate) Where(ps ...predicate.TeamVolunteers) *TeamVolunteersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamVolunteersUpdate) SetTeamID(v uuid.UUID) *TeamVolunteersUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamVolunteersUpdate) SetNillableTeamID(v *uuid.UUID) *TeamVolunteersUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamVolunteersUpdate) SetUserID(v uuid.UUID) *TeamVolunteersUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamVolunteersUpdate) SetNillableUserID(v *uuid.UUID) *TeamVolunteersUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamVolunteersUpdate) SetCreatedAt(v time.Time) *TeamVolunteersUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamVolunteersUpdate) SetNillableCreatedAt(v *time.Time) *TeamVolunteersUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamVolunteersUpdate) SetUpdatedAt(v time.Time) *TeamVolunteersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamVolunteersUpdate) SetTeam(v *Team) *TeamVolunteersUpdate {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamVolunteersUpdate) SetUser(v *User) *TeamVolunteersUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TeamVolunteersMutation object of the builder.
func (_u *TeamVolunteersUpdate) Mutation() *TeamVolunteersMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamVolunteersUpdate) ClearTeam() *TeamVolunteersUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamVolunteersUpdate) ClearUser() *TeamVolunteersUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamVolunteersUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamVolunteersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamVolunteersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamVolunteersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamVolunteersUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamvolunteers.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamVolunteersUpdate) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamVolunteers.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamVolunteers.user"`)
	}
	return nil
}

func (_u *TeamVolunteersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamvolunteers.Table, teamvolunteers.Columns, sqlgraph.NewFieldSpec(teamvolunteers.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamvolunteers.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamvolunteers.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.TeamTable,
			Columns: []string{teamvolunteers.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.TeamTable,
			Columns: []string{teamvolunteers.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.UserTable,
			Columns: []string{teamvolunteers.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.UserTable,
			Columns: []string{teamvolunteers.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamvolunteers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamVolunteersUpdateOne is the builder for updating a single TeamVolunteers entity.
type TeamVolunteersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamVolunteersMutation
}

// SetTeamID sets the "team_id" field.
func (_u *TeamVolunteersUpdateOne) SetTeamID(v uuid.UUID) *TeamVolunteersUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamVolunteersUpdateOne) SetNillableTeamID(v *uuid.UUID) *TeamVolunteersUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamVolunteersUpdateOne) SetUserID(v uuid.UUID) *TeamVolunteersUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamVolunteersUpdateOne) SetNillableUserID(v *uuid.UUID) *TeamVolunteersUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamVolunteersUpdateOne) SetCreatedAt(v time.Time) *TeamVolunteersUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamVolunteersUpdateOne) SetNillableCreatedAt(v *time.Time) *TeamVolunteersUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamVolunteersUpdateOne) SetUpdatedAt(v time.Time) *TeamVolunteersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamVolunteersUpdateOne) SetTeam(v *Team) *TeamVolunteersUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamVolunteersUpdateOne) SetUser(v *User) *TeamVolunteersUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TeamVolunteersMutation object of the builder.
func (_u *TeamVolunteersUpdateOne) Mutation() *TeamVolunteersMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamVolunteersUpdateOne) ClearTeam() *TeamVolunteersUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamVolunteersUpdateOne) ClearUser() *TeamVolunteersUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TeamVolunteersUpdate builder.
func (_u *TeamVolunteersUpdateOne) Where(ps ...predicate.TeamVolunteers) *TeamVolunteersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamVolunteersUpdateOne) Select(field string, fields ...string) *TeamVolunteersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamVolunteers entity.
func (_u *TeamVolunteersUpdateOne) Save(ctx context.Context) (*TeamVolunteers, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamVolunteersUpdateOne) SaveX(ctx context.Context) *TeamVolunteers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamVolunteersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamVolunteersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamVolunteersUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teamvolunteers.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamVolunteersUpdateOne) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamVolunteers.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamVolunteers.user"`)
	}
	return nil
}

func (_u *TeamVolunteersUpdateOne) sqlSave(ctx context.Context) (_node *TeamVolunteers, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamvolunteers.Table, teamvolunteers.Columns, sqlgraph.NewFieldSpec(teamvolunteers.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamVolunteers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamvolunteers.FieldID)
		for _, f := range fields {
			if !teamvolunteers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamvolunteers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamvolunteers.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teamvolunteers.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.TeamTable,
			Columns: []string{teamvolunteers.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.TeamTable,
			Columns: []string{teamvolunteers.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.UserTable,
			Columns: []string{teamvolunteers.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamvolunteers.UserTable,
			Columns: []string{teamvolunteers.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamVolunteers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamvolunteers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
