// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/localchurch"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/ent/teamtodo"
	"github.com/hofchurchng/church-backend/internal/ent/user"
)

// TeamTodoUpdate is the builder for updating TeamTodo entities.
type TeamTodoUpdate struct {
	config
	hooks    []Hook
	mutation *TeamTodoMutation
}

// Where appends a list predicates to the TeamTodoUpdate builder.
func (_u *TeamTodoUpdate) Where(ps ...predicate.TeamTodo) *TeamTodoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChurchID sets the "church_id" field.
func (_u *TeamTodoUpdate) SetChurchID(v uuid.UUID) *TeamTodoUpdate {
	_u.mutation.SetChurchID(v)
	return _u
}

// SetNillableChurchID sets the "church_id" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableChurchID(v *uuid.UUID) *TeamTodoUpdate {
	if v != nil {
		_u.SetChurchID(*v)
	}
	return _u
}

// SetTargetTeam sets the "target_team" field.
func (_u *TeamTodoUpdate) SetTargetTeam(v string) *TeamTodoUpdate {
	_u.mutation.SetTargetTeam(v)
	return _u
}

// SetNillableTargetTeam sets the "target_team" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableTargetTeam(v *string) *TeamTodoUpdate {
	if v != nil {
		_u.SetTargetTeam(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TeamTodoUpdate) SetTitle(v string) *TeamTodoUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableTitle(v *string) *TeamTodoUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TeamTodoUpdate) SetDescription(v string) *TeamTodoUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableDescription(v *string) *TeamTodoUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TeamTodoUpdate) ClearDescription() *TeamTodoUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *TeamTodoUpdate) SetEntityType(v string) *TeamTodoUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableEntityType(v *string) *TeamTodoUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *TeamTodoUpdate) SetEntityID(v uuid.UUID) *TeamTodoUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableEntityID(v *uuid.UUID) *TeamTodoUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamTodoUpdate) SetStatus(v teamtodo.Status) *TeamTodoUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableStatus(v *teamtodo.Status) *TeamTodoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TeamTodoUpdate) SetCreatedBy(v uuid.UUID) *TeamTodoUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableCreatedBy(v *uuid.UUID) *TeamTodoUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetCompletedBy sets the "completed_by" field.
func (_u *TeamTodoUpdate) SetCompletedBy(v uuid.UUID) *TeamTodoUpdate {
	_u.mutation.SetCompletedBy(v)
	return _u
}

// SetNillableCompletedBy sets the "completed_by" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableCompletedBy(v *uuid.UUID) *TeamTodoUpdate {
	if v != nil {
		_u.SetCompletedBy(*v)
	}
	return _u
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (_u *TeamTodoUpdate) ClearCompletedBy() *TeamTodoUpdate {
	_u.mutation.ClearCompletedBy()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TeamTodoUpdate) SetCompletedAt(v time.Time) *TeamTodoUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TeamTodoUpdate) SetNillableCompletedAt(v *time.Time) *TeamTodoUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TeamTodoUpdate) ClearCompletedAt() *TeamTodoUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetChurch sets the "church" edge to the LocalChurch entity.
func (_u *TeamTodoUpdate) SetChurch(v *LocalChurch) *TeamTodoUpdate {
	return _u.SetChurchID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TeamTodoUpdate) SetCreatorID(id uuid.UUID) *TeamTodoUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TeamTodoUpdate) SetCreator(v *User) *TeamTodoUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the TeamTodoMutation object of the builder.
func (_u *TeamTodoUpdate) Mutation() *TeamTodoMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the LocalChurch entity.
func (_u *TeamTodoUpdate) ClearChurch() *TeamTodoUpdate {
	_u.mutation.ClearChurch()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TeamTodoUpdate) ClearCreator() *TeamTodoUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamTodoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamTodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamTodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamTodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamTodoUpdate) check() error {
	if v, ok := _u.mutation.TargetTeam(); ok {
		if err := teamtodo.TargetTeamValidator(v); err != nil {
			return &ValidationError{Name: "target_team", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.target_team": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := teamtodo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := teamtodo.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teamtodo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.status": %w`, err)}
		}
	}
	if _u.mutation.ChurchCleared() && len(_u.mutation.ChurchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamTodo.church"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamTodo.creator"`)
	}
	return nil
}

func (_u *TeamTodoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamtodo.Table, teamtodo.Columns, sqlgraph.NewFieldSpec(teamtodo.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetTeam(); ok {
		_spec.SetField(teamtodo.FieldTargetTeam, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(teamtodo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(teamtodo.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(teamtodo.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(teamtodo.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(teamtodo.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teamtodo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CompletedBy(); ok {
		_spec.SetField(teamtodo.FieldCompletedBy, field.TypeUUID, value)
	}
	if _u.mutation.CompletedByCleared() {
		_spec.ClearField(teamtodo.FieldCompletedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(teamtodo.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(teamtodo.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.ChurchTable,
			Columns: []string{teamtodo.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.ChurchTable,
			Columns: []string{teamtodo.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.CreatorTable,
			Columns: []string{teamtodo.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.CreatorTable,
			Columns: []string{teamtodo.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamtodo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamTodoUpdateOne is the builder for updating a single TeamTodo entity.
type TeamTodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamTodoMutation
}

// SetChurchID sets the "church_id" field.
func (_u *TeamTodoUpdateOne) SetChurchID(v uuid.UUID) *TeamTodoUpdateOne {
	_u.mutation.SetChurchID(v)
	return _u
}

// SetNillableChurchID sets the "church_id" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableChurchID(v *uuid.UUID) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetChurchID(*v)
	}
	return _u
}

// SetTargetTeam sets the "target_team" field.
func (_u *TeamTodoUpdateOne) SetTargetTeam(v string) *TeamTodoUpdateOne {
	_u.mutation.SetTargetTeam(v)
	return _u
}

// SetNillableTargetTeam sets the "target_team" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableTargetTeam(v *string) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetTargetTeam(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TeamTodoUpdateOne) SetTitle(v string) *TeamTodoUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableTitle(v *string) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TeamTodoUpdateOne) SetDescription(v string) *TeamTodoUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableDescription(v *string) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TeamTodoUpdateOne) ClearDescription() *TeamTodoUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *TeamTodoUpdateOne) SetEntityType(v string) *TeamTodoUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableEntityType(v *string) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *TeamTodoUpdateOne) SetEntityID(v uuid.UUID) *TeamTodoUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableEntityID(v *uuid.UUID) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamTodoUpdateOne) SetStatus(v teamtodo.Status) *TeamTodoUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableStatus(v *teamtodo.Status) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TeamTodoUpdateOne) SetCreatedBy(v uuid.UUID) *TeamTodoUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetCompletedBy sets the "completed_by" field.
func (_u *TeamTodoUpdateOne) SetCompletedBy(v uuid.UUID) *TeamTodoUpdateOne {
	_u.mutation.SetCompletedBy(v)
	return _u
}

// SetNillableCompletedBy sets the "completed_by" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableCompletedBy(v *uuid.UUID) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetCompletedBy(*v)
	}
	return _u
}

// ClearCompletedBy clears the value of the "completed_by" field.
func (_u *TeamTodoUpdateOne) ClearCompletedBy() *TeamTodoUpdateOne {
	_u.mutation.ClearCompletedBy()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *TeamTodoUpdateOne) SetCompletedAt(v time.Time) *TeamTodoUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *TeamTodoUpdateOne) SetNillableCompletedAt(v *time.Time) *TeamTodoUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *TeamTodoUpdateOne) ClearCompletedAt() *TeamTodoUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetChurch sets the "church" edge to the LocalChurch entity.
func (_u *TeamTodoUpdateOne) SetChurch(v *LocalChurch) *TeamTodoUpdateOne {
	return _u.SetChurchID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *TeamTodoUpdateOne) SetCreatorID(id uuid.UUID) *TeamTodoUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TeamTodoUpdateOne) SetCreator(v *User) *TeamTodoUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the TeamTodoMutation object of the builder.
func (_u *TeamTodoUpdateOne) Mutation() *TeamTodoMutation {
	return _u.mutation
}

// ClearChurch clears the "church" edge to the LocalChurch entity.
func (_u *TeamTodoUpdateOne) ClearChurch() *TeamTodoUpdateOne {
	_u.mutation.ClearChurch()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TeamTodoUpdateOne) ClearCreator() *TeamTodoUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the TeamTodoUpdate builder.
func (_u *TeamTodoUpdateOne) Where(ps ...predicate.TeamTodo) *TeamTodoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamTodoUpdateOne) Select(field string, fields ...string) *TeamTodoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamTodo entity.
func (_u *TeamTodoUpdateOne) Save(ctx context.Context) (*TeamTodo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamTodoUpdateOne) SaveX(ctx context.Context) *TeamTodo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamTodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamTodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamTodoUpdateOne) check() error {
	if v, ok := _u.mutation.TargetTeam(); ok {
		if err := teamtodo.TargetTeamValidator(v); err != nil {
			return &ValidationError{Name: "target_team", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.target_team": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := teamtodo.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := teamtodo.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.entity_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teamtodo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamTodo.status": %w`, err)}
		}
	}
	if _u.mutation.ChurchCleared() && len(_u.mutation.ChurchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamTodo.church"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamTodo.creator"`)
	}
	return nil
}

func (_u *TeamTodoUpdateOne) sqlSave(ctx context.Context) (_node *TeamTodo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamtodo.Table, teamtodo.Columns, sqlgraph.NewFieldSpec(teamtodo.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamTodo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamtodo.FieldID)
		for _, f := range fields {
			if !teamtodo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamtodo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetTeam(); ok {
		_spec.SetField(teamtodo.FieldTargetTeam, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(teamtodo.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(teamtodo.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(teamtodo.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(teamtodo.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(teamtodo.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teamtodo.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CompletedBy(); ok {
		_spec.SetField(teamtodo.FieldCompletedBy, field.TypeUUID, value)
	}
	if _u.mutation.CompletedByCleared() {
		_spec.ClearField(teamtodo.FieldCompletedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(teamtodo.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(teamtodo.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.ChurchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.ChurchTable,
			Columns: []string{teamtodo.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChurchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.ChurchTable,
			Columns: []string{teamtodo.ChurchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(localchurch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.CreatorTable,
			Columns: []string{teamtodo.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtodo.CreatorTable,
			Columns: []string{teamtodo.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamTodo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamtodo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
