// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/ent/transportrequest"
)

// TransportRequestDelete is the builder for deleting a TransportRequest entity.
type TransportRequestDelete struct {
	config
	hooks    []Hook
	mutation *TransportRequestMutation
}

// Where appends a list predicates to the TransportRequestDelete builder.
func (_d *TransportRequestDelete) Where(ps ...predicate.TransportRequest) *TransportRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TransportRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TransportRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TransportRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(transportrequest.Table, sqlgraph.NewFieldSpec(transportrequest.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TransportRequestDeleteOne is the builder for deleting a single TransportRequest entity.
type TransportRequestDeleteOne struct {
	_d *TransportRequestDelete
}

// Where appends a list predicates to the TransportRequestDelete builder.
func (_d *TransportRequestDeleteOne) Where(ps ...predicate.TransportRequest) *TransportRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TransportRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transportrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TransportRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
