// Code generated by ent, DO NOT EDIT.

package profilechangerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldID, id))
}

// ChurchID applies equality check predicate on the "church_id" field. It's identical to ChurchIDEQ.
func ChurchID(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldChurchID, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldMemberID, v))
}

// RequestedByUserID applies equality check predicate on the "requested_by_user_id" field. It's identical to RequestedByUserIDEQ.
func RequestedByUserID(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldRequestedByUserID, v))
}

// ReviewedByUserID applies equality check predicate on the "reviewed_by_user_id" field. It's identical to ReviewedByUserIDEQ.
func ReviewedByUserID(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldReviewedByUserID, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldPayloadJSON, v))
}

// RejectionReason applies equality check predicate on the "rejection_reason" field. It's identical to RejectionReasonEQ.
func RejectionReason(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldRejectionReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ChurchIDEQ applies the EQ predicate on the "church_id" field.
func ChurchIDEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldChurchID, v))
}

// ChurchIDNEQ applies the NEQ predicate on the "church_id" field.
func ChurchIDNEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldChurchID, v))
}

// ChurchIDIn applies the In predicate on the "church_id" field.
func ChurchIDIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldChurchID, vs...))
}

// ChurchIDNotIn applies the NotIn predicate on the "church_id" field.
func ChurchIDNotIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldChurchID, vs...))
}

// ChurchIDGT applies the GT predicate on the "church_id" field.
func ChurchIDGT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldChurchID, v))
}

// ChurchIDGTE applies the GTE predicate on the "church_id" field.
func ChurchIDGTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldChurchID, v))
}

// ChurchIDLT applies the LT predicate on the "church_id" field.
func ChurchIDLT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldChurchID, v))
}

// ChurchIDLTE applies the LTE predicate on the "church_id" field.
func ChurchIDLTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldChurchID, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "member_id" field.
func MemberIDGT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "member_id" field.
func MemberIDGTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "member_id" field.
func MemberIDLT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "member_id" field.
func MemberIDLTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldMemberID, v))
}

// RequestedByUserIDEQ applies the EQ predicate on the "requested_by_user_id" field.
func RequestedByUserIDEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldRequestedByUserID, v))
}

// RequestedByUserIDNEQ applies the NEQ predicate on the "requested_by_user_id" field.
func RequestedByUserIDNEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldRequestedByUserID, v))
}

// RequestedByUserIDIn applies the In predicate on the "requested_by_user_id" field.
func RequestedByUserIDIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldRequestedByUserID, vs...))
}

// RequestedByUserIDNotIn applies the NotIn predicate on the "requested_by_user_id" field.
func RequestedByUserIDNotIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldRequestedByUserID, vs...))
}

// RequestedByUserIDGT applies the GT predicate on the "requested_by_user_id" field.
func RequestedByUserIDGT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldRequestedByUserID, v))
}

// RequestedByUserIDGTE applies the GTE predicate on the "requested_by_user_id" field.
func RequestedByUserIDGTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldRequestedByUserID, v))
}

// RequestedByUserIDLT applies the LT predicate on the "requested_by_user_id" field.
func RequestedByUserIDLT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldRequestedByUserID, v))
}

// RequestedByUserIDLTE applies the LTE predicate on the "requested_by_user_id" field.
func RequestedByUserIDLTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldRequestedByUserID, v))
}

// ReviewedByUserIDEQ applies the EQ predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldReviewedByUserID, v))
}

// ReviewedByUserIDNEQ applies the NEQ predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNEQ(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldReviewedByUserID, v))
}

// ReviewedByUserIDIn applies the In predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldReviewedByUserID, vs...))
}

// ReviewedByUserIDNotIn applies the NotIn predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNotIn(vs ...uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldReviewedByUserID, vs...))
}

// ReviewedByUserIDGT applies the GT predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDGT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldReviewedByUserID, v))
}

// ReviewedByUserIDGTE applies the GTE predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDGTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldReviewedByUserID, v))
}

// ReviewedByUserIDLT applies the LT predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDLT(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldReviewedByUserID, v))
}

// ReviewedByUserIDLTE applies the LTE predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDLTE(v uuid.UUID) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldReviewedByUserID, v))
}

// ReviewedByUserIDIsNil applies the IsNil predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDIsNil() predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIsNull(FieldReviewedByUserID))
}

// ReviewedByUserIDNotNil applies the NotNil predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNotNil() predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotNull(FieldReviewedByUserID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldPayloadJSON, v))
}

// PayloadJSONContains applies the Contains predicate on the "payload_json" field.
func PayloadJSONContains(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldContains(FieldPayloadJSON, v))
}

// PayloadJSONHasPrefix applies the HasPrefix predicate on the "payload_json" field.
func PayloadJSONHasPrefix(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldHasPrefix(FieldPayloadJSON, v))
}

// PayloadJSONHasSuffix applies the HasSuffix predicate on the "payload_json" field.
func PayloadJSONHasSuffix(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldHasSuffix(FieldPayloadJSON, v))
}

// PayloadJSONEqualFold applies the EqualFold predicate on the "payload_json" field.
func PayloadJSONEqualFold(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEqualFold(FieldPayloadJSON, v))
}

// PayloadJSONContainsFold applies the ContainsFold predicate on the "payload_json" field.
func PayloadJSONContainsFold(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldContainsFold(FieldPayloadJSON, v))
}

// RejectionReasonEQ applies the EQ predicate on the "rejection_reason" field.
func RejectionReasonEQ(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldRejectionReason, v))
}

// RejectionReasonNEQ applies the NEQ predicate on the "rejection_reason" field.
func RejectionReasonNEQ(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldRejectionReason, v))
}

// RejectionReasonIn applies the In predicate on the "rejection_reason" field.
func RejectionReasonIn(vs ...string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldRejectionReason, vs...))
}

// RejectionReasonNotIn applies the NotIn predicate on the "rejection_reason" field.
func RejectionReasonNotIn(vs ...string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldRejectionReason, vs...))
}

// RejectionReasonGT applies the GT predicate on the "rejection_reason" field.
func RejectionReasonGT(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldRejectionReason, v))
}

// RejectionReasonGTE applies the GTE predicate on the "rejection_reason" field.
func RejectionReasonGTE(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldRejectionReason, v))
}

// RejectionReasonLT applies the LT predicate on the "rejection_reason" field.
func RejectionReasonLT(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldRejectionReason, v))
}

// RejectionReasonLTE applies the LTE predicate on the "rejection_reason" field.
func RejectionReasonLTE(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldRejectionReason, v))
}

// RejectionReasonContains applies the Contains predicate on the "rejection_reason" field.
func RejectionReasonContains(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldContains(FieldRejectionReason, v))
}

// RejectionReasonHasPrefix applies the HasPrefix predicate on the "rejection_reason" field.
func RejectionReasonHasPrefix(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldHasPrefix(FieldRejectionReason, v))
}

// RejectionReasonHasSuffix applies the HasSuffix predicate on the "rejection_reason" field.
func RejectionReasonHasSuffix(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldHasSuffix(FieldRejectionReason, v))
}

// RejectionReasonIsNil applies the IsNil predicate on the "rejection_reason" field.
func RejectionReasonIsNil() predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIsNull(FieldRejectionReason))
}

// RejectionReasonNotNil applies the NotNil predicate on the "rejection_reason" field.
func RejectionReasonNotNil() predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotNull(FieldRejectionReason))
}

// RejectionReasonEqualFold applies the EqualFold predicate on the "rejection_reason" field.
func RejectionReasonEqualFold(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEqualFold(FieldRejectionReason, v))
}

// RejectionReasonContainsFold applies the ContainsFold predicate on the "rejection_reason" field.
func RejectionReasonContainsFold(v string) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldContainsFold(FieldRejectionReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.FieldNotNull(FieldReviewedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProfileChangeRequest) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProfileChangeRequest) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProfileChangeRequest) predicate.ProfileChangeRequest {
	return predicate.ProfileChangeRequest(sql.NotPredicates(p))
}
