// Code generated by ent, DO NOT EDIT.

package membertransfer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldID, id))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldMemberID, v))
}

// OriginChurchID applies equality check predicate on the "origin_church_id" field. It's identical to OriginChurchIDEQ.
func OriginChurchID(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldOriginChurchID, v))
}

// DestinationChurchID applies equality check predicate on the "destination_church_id" field. It's identical to DestinationChurchIDEQ.
func DestinationChurchID(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldDestinationChurchID, v))
}

// TransferReason applies equality check predicate on the "transfer_reason" field. It's identical to TransferReasonEQ.
func TransferReason(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldTransferReason, v))
}

// PastoralRecommendation applies equality check predicate on the "pastoral_recommendation" field. It's identical to PastoralRecommendationEQ.
func PastoralRecommendation(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldPastoralRecommendation, v))
}

// InitiatedByUserID applies equality check predicate on the "initiated_by_user_id" field. It's identical to InitiatedByUserIDEQ.
func InitiatedByUserID(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldInitiatedByUserID, v))
}

// ReviewedByUserID applies equality check predicate on the "reviewed_by_user_id" field. It's identical to ReviewedByUserIDEQ.
func ReviewedByUserID(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldReviewedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldReviewedAt, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "member_id" field.
func MemberIDGT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "member_id" field.
func MemberIDGTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "member_id" field.
func MemberIDLT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "member_id" field.
func MemberIDLTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldMemberID, v))
}

// OriginChurchIDEQ applies the EQ predicate on the "origin_church_id" field.
func OriginChurchIDEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldOriginChurchID, v))
}

// OriginChurchIDNEQ applies the NEQ predicate on the "origin_church_id" field.
func OriginChurchIDNEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldOriginChurchID, v))
}

// OriginChurchIDIn applies the In predicate on the "origin_church_id" field.
func OriginChurchIDIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldOriginChurchID, vs...))
}

// OriginChurchIDNotIn applies the NotIn predicate on the "origin_church_id" field.
func OriginChurchIDNotIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldOriginChurchID, vs...))
}

// OriginChurchIDGT applies the GT predicate on the "origin_church_id" field.
func OriginChurchIDGT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldOriginChurchID, v))
}

// OriginChurchIDGTE applies the GTE predicate on the "origin_church_id" field.
func OriginChurchIDGTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldOriginChurchID, v))
}

// OriginChurchIDLT applies the LT predicate on the "origin_church_id" field.
func OriginChurchIDLT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldOriginChurchID, v))
}

// OriginChurchIDLTE applies the LTE predicate on the "origin_church_id" field.
func OriginChurchIDLTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldOriginChurchID, v))
}

// DestinationChurchIDEQ applies the EQ predicate on the "destination_church_id" field.
func DestinationChurchIDEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldDestinationChurchID, v))
}

// DestinationChurchIDNEQ applies the NEQ predicate on the "destination_church_id" field.
func DestinationChurchIDNEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldDestinationChurchID, v))
}

// DestinationChurchIDIn applies the In predicate on the "destination_church_id" field.
func DestinationChurchIDIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldDestinationChurchID, vs...))
}

// DestinationChurchIDNotIn applies the NotIn predicate on the "destination_church_id" field.
func DestinationChurchIDNotIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldDestinationChurchID, vs...))
}

// DestinationChurchIDGT applies the GT predicate on the "destination_church_id" field.
func DestinationChurchIDGT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldDestinationChurchID, v))
}

// DestinationChurchIDGTE applies the GTE predicate on the "destination_church_id" field.
func DestinationChurchIDGTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldDestinationChurchID, v))
}

// DestinationChurchIDLT applies the LT predicate on the "destination_church_id" field.
func DestinationChurchIDLT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldDestinationChurchID, v))
}

// DestinationChurchIDLTE applies the LTE predicate on the "destination_church_id" field.
func DestinationChurchIDLTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldDestinationChurchID, v))
}

// TransferReasonEQ applies the EQ predicate on the "transfer_reason" field.
func TransferReasonEQ(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldTransferReason, v))
}

// TransferReasonNEQ applies the NEQ predicate on the "transfer_reason" field.
func TransferReasonNEQ(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldTransferReason, v))
}

// TransferReasonIn applies the In predicate on the "transfer_reason" field.
func TransferReasonIn(vs ...string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldTransferReason, vs...))
}

// TransferReasonNotIn applies the NotIn predicate on the "transfer_reason" field.
func TransferReasonNotIn(vs ...string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldTransferReason, vs...))
}

// TransferReasonGT applies the GT predicate on the "transfer_reason" field.
func TransferReasonGT(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldTransferReason, v))
}

// TransferReasonGTE applies the GTE predicate on the "transfer_reason" field.
func TransferReasonGTE(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldTransferReason, v))
}

// TransferReasonLT applies the LT predicate on the "transfer_reason" field.
func TransferReasonLT(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldTransferReason, v))
}

// TransferReasonLTE applies the LTE predicate on the "transfer_reason" field.
func TransferReasonLTE(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldTransferReason, v))
}

// TransferReasonContains applies the Contains predicate on the "transfer_reason" field.
func TransferReasonContains(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldContains(FieldTransferReason, v))
}

// TransferReasonHasPrefix applies the HasPrefix predicate on the "transfer_reason" field.
func TransferReasonHasPrefix(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldHasPrefix(FieldTransferReason, v))
}

// TransferReasonHasSuffix applies the HasSuffix predicate on the "transfer_reason" field.
func TransferReasonHasSuffix(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldHasSuffix(FieldTransferReason, v))
}

// TransferReasonIsNil applies the IsNil predicate on the "transfer_reason" field.
func TransferReasonIsNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIsNull(FieldTransferReason))
}

// TransferReasonNotNil applies the NotNil predicate on the "transfer_reason" field.
func TransferReasonNotNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotNull(FieldTransferReason))
}

// TransferReasonEqualFold applies the EqualFold predicate on the "transfer_reason" field.
func TransferReasonEqualFold(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEqualFold(FieldTransferReason, v))
}

// TransferReasonContainsFold applies the ContainsFold predicate on the "transfer_reason" field.
func TransferReasonContainsFold(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldContainsFold(FieldTransferReason, v))
}

// PastoralRecommendationEQ applies the EQ predicate on the "pastoral_recommendation" field.
func PastoralRecommendationEQ(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldPastoralRecommendation, v))
}

// PastoralRecommendationNEQ applies the NEQ predicate on the "pastoral_recommendation" field.
func PastoralRecommendationNEQ(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldPastoralRecommendation, v))
}

// PastoralRecommendationIn applies the In predicate on the "pastoral_recommendation" field.
func PastoralRecommendationIn(vs ...string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldPastoralRecommendation, vs...))
}

// PastoralRecommendationNotIn applies the NotIn predicate on the "pastoral_recommendation" field.
func PastoralRecommendationNotIn(vs ...string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldPastoralRecommendation, vs...))
}

// PastoralRecommendationGT applies the GT predicate on the "pastoral_recommendation" field.
func PastoralRecommendationGT(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldPastoralRecommendation, v))
}

// PastoralRecommendationGTE applies the GTE predicate on the "pastoral_recommendation" field.
func PastoralRecommendationGTE(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldPastoralRecommendation, v))
}

// PastoralRecommendationLT applies the LT predicate on the "pastoral_recommendation" field.
func PastoralRecommendationLT(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldPastoralRecommendation, v))
}

// PastoralRecommendationLTE applies the LTE predicate on the "pastoral_recommendation" field.
func PastoralRecommendationLTE(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldPastoralRecommendation, v))
}

// PastoralRecommendationContains applies the Contains predicate on the "pastoral_recommendation" field.
func PastoralRecommendationContains(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldContains(FieldPastoralRecommendation, v))
}

// PastoralRecommendationHasPrefix applies the HasPrefix predicate on the "pastoral_recommendation" field.
func PastoralRecommendationHasPrefix(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldHasPrefix(FieldPastoralRecommendation, v))
}

// PastoralRecommendationHasSuffix applies the HasSuffix predicate on the "pastoral_recommendation" field.
func PastoralRecommendationHasSuffix(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldHasSuffix(FieldPastoralRecommendation, v))
}

// PastoralRecommendationIsNil applies the IsNil predicate on the "pastoral_recommendation" field.
func PastoralRecommendationIsNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIsNull(FieldPastoralRecommendation))
}

// PastoralRecommendationNotNil applies the NotNil predicate on the "pastoral_recommendation" field.
func PastoralRecommendationNotNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotNull(FieldPastoralRecommendation))
}

// PastoralRecommendationEqualFold applies the EqualFold predicate on the "pastoral_recommendation" field.
func PastoralRecommendationEqualFold(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEqualFold(FieldPastoralRecommendation, v))
}

// PastoralRecommendationContainsFold applies the ContainsFold predicate on the "pastoral_recommendation" field.
func PastoralRecommendationContainsFold(v string) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldContainsFold(FieldPastoralRecommendation, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldStatus, vs...))
}

// InitiatedByUserIDEQ applies the EQ predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDNEQ applies the NEQ predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDNEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDIn applies the In predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldInitiatedByUserID, vs...))
}

// InitiatedByUserIDNotIn applies the NotIn predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDNotIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldInitiatedByUserID, vs...))
}

// InitiatedByUserIDGT applies the GT predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDGT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDGTE applies the GTE predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDGTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDLT applies the LT predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDLT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldInitiatedByUserID, v))
}

// InitiatedByUserIDLTE applies the LTE predicate on the "initiated_by_user_id" field.
func InitiatedByUserIDLTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldInitiatedByUserID, v))
}

// ReviewedByUserIDEQ applies the EQ predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldReviewedByUserID, v))
}

// ReviewedByUserIDNEQ applies the NEQ predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNEQ(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldReviewedByUserID, v))
}

// ReviewedByUserIDIn applies the In predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldReviewedByUserID, vs...))
}

// ReviewedByUserIDNotIn applies the NotIn predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNotIn(vs ...uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldReviewedByUserID, vs...))
}

// ReviewedByUserIDGT applies the GT predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDGT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldReviewedByUserID, v))
}

// ReviewedByUserIDGTE applies the GTE predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDGTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldReviewedByUserID, v))
}

// ReviewedByUserIDLT applies the LT predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDLT(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldReviewedByUserID, v))
}

// ReviewedByUserIDLTE applies the LTE predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDLTE(v uuid.UUID) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldReviewedByUserID, v))
}

// ReviewedByUserIDIsNil applies the IsNil predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDIsNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIsNull(FieldReviewedByUserID))
}

// ReviewedByUserIDNotNil applies the NotNil predicate on the "reviewed_by_user_id" field.
func ReviewedByUserIDNotNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotNull(FieldReviewedByUserID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldCreatedAt, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.FieldNotNull(FieldReviewedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemberTransfer) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemberTransfer) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemberTransfer) predicate.MemberTransfer {
	return predicate.MemberTransfer(sql.NotPredicates(p))
}
