// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/v2/ent/account"
	"github.com/hofchurchng/church-backend/internal/v2/ent/baselinegrant"
	"github.com/hofchurchng/church-backend/internal/v2/ent/capability"
	"github.com/hofchurchng/church-backend/internal/v2/ent/predicate"
)

// BaselineGrantUpdate is the builder for updating BaselineGrant entities.
type BaselineGrantUpdate struct {
	config
	hooks    []Hook
	mutation *BaselineGrantMutation
}

// Where appends a list predicates to the BaselineGrantUpdate builder.
func (_u *BaselineGrantUpdate) Where(ps ...predicate.BaselineGrant) *BaselineGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *BaselineGrantUpdate) SetVersion(v int) *BaselineGrantUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableVersion(v *int) *BaselineGrantUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *BaselineGrantUpdate) AddVersion(v int) *BaselineGrantUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BaselineGrantUpdate) SetUpdatedAt(v time.Time) *BaselineGrantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableUpdatedAt(v *time.Time) *BaselineGrantUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *BaselineGrantUpdate) SetOrganizationID(v uuid.UUID) *BaselineGrantUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableOrganizationID(v *uuid.UUID) *BaselineGrantUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *BaselineGrantUpdate) SetAccountID(v uuid.UUID) *BaselineGrantUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableAccountID(v *uuid.UUID) *BaselineGrantUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetCapabilityID sets the "capability_id" field.
func (_u *BaselineGrantUpdate) SetCapabilityID(v uuid.UUID) *BaselineGrantUpdate {
	_u.mutation.SetCapabilityID(v)
	return _u
}

// SetNillableCapabilityID sets the "capability_id" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableCapabilityID(v *uuid.UUID) *BaselineGrantUpdate {
	if v != nil {
		_u.SetCapabilityID(*v)
	}
	return _u
}

// SetScopeLevel sets the "scope_level" field.
func (_u *BaselineGrantUpdate) SetScopeLevel(v string) *BaselineGrantUpdate {
	_u.mutation.SetScopeLevel(v)
	return _u
}

// SetNillableScopeLevel sets the "scope_level" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableScopeLevel(v *string) *BaselineGrantUpdate {
	if v != nil {
		_u.SetScopeLevel(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BaselineGrantUpdate) SetCreatedAt(v time.Time) *BaselineGrantUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BaselineGrantUpdate) SetNillableCreatedAt(v *time.Time) *BaselineGrantUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *BaselineGrantUpdate) SetAccount(v *Account) *BaselineGrantUpdate {
	return _u.SetAccountID(v.ID)
}

// SetCapability sets the "capability" edge to the Capability entity.
func (_u *BaselineGrantUpdate) SetCapability(v *Capability) *BaselineGrantUpdate {
	return _u.SetCapabilityID(v.ID)
}

// Mutation returns the BaselineGrantMutation object of the builder.
func (_u *BaselineGrantUpdate) Mutation() *BaselineGrantMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *BaselineGrantUpdate) ClearAccount() *BaselineGrantUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearCapability clears the "capability" edge to the Capability entity.
func (_u *BaselineGrantUpdate) ClearCapability() *BaselineGrantUpdate {
	_u.mutation.ClearCapability()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BaselineGrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BaselineGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BaselineGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BaselineGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BaselineGrantUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := baselinegrant.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "BaselineGrant.version": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BaselineGrant.account"`)
	}
	if _u.mutation.CapabilityCleared() && len(_u.mutation.CapabilityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BaselineGrant.capability"`)
	}
	return nil
}

func (_u *BaselineGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(baselinegrant.Table, baselinegrant.Columns, sqlgraph.NewFieldSpec(baselinegrant.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(baselinegrant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(baselinegrant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(baselinegrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(baselinegrant.FieldOrganizationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ScopeLevel(); ok {
		_spec.SetField(baselinegrant.FieldScopeLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(baselinegrant.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.AccountTable,
			Columns: []string{baselinegrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.AccountTable,
			Columns: []string{baselinegrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CapabilityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.CapabilityTable,
			Columns: []string{baselinegrant.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapabilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.CapabilityTable,
			Columns: []string{baselinegrant.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{baselinegrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BaselineGrantUpdateOne is the builder for updating a single BaselineGrant entity.
type BaselineGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BaselineGrantMutation
}

// SetVersion sets the "version" field.
func (_u *BaselineGrantUpdateOne) SetVersion(v int) *BaselineGrantUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableVersion(v *int) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *BaselineGrantUpdateOne) AddVersion(v int) *BaselineGrantUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BaselineGrantUpdateOne) SetUpdatedAt(v time.Time) *BaselineGrantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableUpdatedAt(v *time.Time) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *BaselineGrantUpdateOne) SetOrganizationID(v uuid.UUID) *BaselineGrantUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *BaselineGrantUpdateOne) SetAccountID(v uuid.UUID) *BaselineGrantUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableAccountID(v *uuid.UUID) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetCapabilityID sets the "capability_id" field.
func (_u *BaselineGrantUpdateOne) SetCapabilityID(v uuid.UUID) *BaselineGrantUpdateOne {
	_u.mutation.SetCapabilityID(v)
	return _u
}

// SetNillableCapabilityID sets the "capability_id" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableCapabilityID(v *uuid.UUID) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetCapabilityID(*v)
	}
	return _u
}

// SetScopeLevel sets the "scope_level" field.
func (_u *BaselineGrantUpdateOne) SetScopeLevel(v string) *BaselineGrantUpdateOne {
	_u.mutation.SetScopeLevel(v)
	return _u
}

// SetNillableScopeLevel sets the "scope_level" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableScopeLevel(v *string) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetScopeLevel(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BaselineGrantUpdateOne) SetCreatedAt(v time.Time) *BaselineGrantUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BaselineGrantUpdateOne) SetNillableCreatedAt(v *time.Time) *BaselineGrantUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *BaselineGrantUpdateOne) SetAccount(v *Account) *BaselineGrantUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetCapability sets the "capability" edge to the Capability entity.
func (_u *BaselineGrantUpdateOne) SetCapability(v *Capability) *BaselineGrantUpdateOne {
	return _u.SetCapabilityID(v.ID)
}

// Mutation returns the BaselineGrantMutation object of the builder.
func (_u *BaselineGrantUpdateOne) Mutation() *BaselineGrantMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *BaselineGrantUpdateOne) ClearAccount() *BaselineGrantUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearCapability clears the "capability" edge to the Capability entity.
func (_u *BaselineGrantUpdateOne) ClearCapability() *BaselineGrantUpdateOne {
	_u.mutation.ClearCapability()
	return _u
}

// Where appends a list predicates to the BaselineGrantUpdate builder.
func (_u *BaselineGrantUpdateOne) Where(ps ...predicate.BaselineGrant) *BaselineGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BaselineGrantUpdateOne) Select(field string, fields ...string) *BaselineGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BaselineGrant entity.
func (_u *BaselineGrantUpdateOne) Save(ctx context.Context) (*BaselineGrant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BaselineGrantUpdateOne) SaveX(ctx context.Context) *BaselineGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BaselineGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BaselineGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BaselineGrantUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := baselinegrant.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "BaselineGrant.version": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BaselineGrant.account"`)
	}
	if _u.mutation.CapabilityCleared() && len(_u.mutation.CapabilityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BaselineGrant.capability"`)
	}
	return nil
}

func (_u *BaselineGrantUpdateOne) sqlSave(ctx context.Context) (_node *BaselineGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(baselinegrant.Table, baselinegrant.Columns, sqlgraph.NewFieldSpec(baselinegrant.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BaselineGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, baselinegrant.FieldID)
		for _, f := range fields {
			if !baselinegrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != baselinegrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(baselinegrant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(baselinegrant.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(baselinegrant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(baselinegrant.FieldOrganizationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ScopeLevel(); ok {
		_spec.SetField(baselinegrant.FieldScopeLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(baselinegrant.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.AccountTable,
			Columns: []string{baselinegrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.AccountTable,
			Columns: []string{baselinegrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CapabilityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.CapabilityTable,
			Columns: []string{baselinegrant.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CapabilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   baselinegrant.CapabilityTable,
			Columns: []string{baselinegrant.CapabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(capability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BaselineGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{baselinegrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
