// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/v2/ent/account"
	"github.com/hofchurchng/church-backend/internal/v2/ent/assignment"
	"github.com/hofchurchng/church-backend/internal/v2/ent/churchaffiliation"
	"github.com/hofchurchng/church-backend/internal/v2/ent/contactpoint"
	"github.com/hofchurchng/church-backend/internal/v2/ent/organization"
	"github.com/hofchurchng/church-backend/internal/v2/ent/person"
)

// PersonCreate is the builder for creating a Person entity.
type PersonCreate struct {
	config
	mutation *PersonMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (_c *PersonCreate) SetVersion(v int) *PersonCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *PersonCreate) SetNillableVersion(v *int) *PersonCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *PersonCreate) SetOrganizationID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetFirstName sets the "first_name" field.
func (_c *PersonCreate) SetFirstName(v string) *PersonCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_c *PersonCreate) SetNillableFirstName(v *string) *PersonCreate {
	if v != nil {
		_c.SetFirstName(*v)
	}
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *PersonCreate) SetLastName(v string) *PersonCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_c *PersonCreate) SetNillableLastName(v *string) *PersonCreate {
	if v != nil {
		_c.SetLastName(*v)
	}
	return _c
}

// SetIdentityStatus sets the "identity_status" field.
func (_c *PersonCreate) SetIdentityStatus(v string) *PersonCreate {
	_c.mutation.SetIdentityStatus(v)
	return _c
}

// SetNillableIdentityStatus sets the "identity_status" field if the given value is not nil.
func (_c *PersonCreate) SetNillableIdentityStatus(v *string) *PersonCreate {
	if v != nil {
		_c.SetIdentityStatus(*v)
	}
	return _c
}

// SetMergedIntoPersonID sets the "merged_into_person_id" field.
func (_c *PersonCreate) SetMergedIntoPersonID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetMergedIntoPersonID(v)
	return _c
}

// SetNillableMergedIntoPersonID sets the "merged_into_person_id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableMergedIntoPersonID(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetMergedIntoPersonID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PersonCreate) SetCreatedAt(v time.Time) *PersonCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PersonCreate) SetNillableCreatedAt(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PersonCreate) SetUpdatedAt(v time.Time) *PersonCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PersonCreate) SetNillableUpdatedAt(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PersonCreate) SetID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableID(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *PersonCreate) SetOrganization(v *Organization) *PersonCreate {
	return _c.SetOrganizationID(v.ID)
}

// AddContactPointIDs adds the "contact_points" edge to the ContactPoint entity by IDs.
func (_c *PersonCreate) AddContactPointIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddContactPointIDs(ids...)
	return _c
}

// AddContactPoints adds the "contact_points" edges to the ContactPoint entity.
func (_c *PersonCreate) AddContactPoints(v ...*ContactPoint) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddContactPointIDs(ids...)
}

// AddAffiliationIDs adds the "affiliations" edge to the ChurchAffiliation entity by IDs.
func (_c *PersonCreate) AddAffiliationIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddAffiliationIDs(ids...)
	return _c
}

// AddAffiliations adds the "affiliations" edges to the ChurchAffiliation entity.
func (_c *PersonCreate) AddAffiliations(v ...*ChurchAffiliation) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAffiliationIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *PersonCreate) AddAccountIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *PersonCreate) AddAccounts(v ...*Account) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the Assignment entity by IDs.
func (_c *PersonCreate) AddAssignmentIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddAssignmentIDs(ids...)
	return _c
}

// AddAssignments adds the "assignments" edges to the Assignment entity.
func (_c *PersonCreate) AddAssignments(v ...*Assignment) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignmentIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_c *PersonCreate) Mutation() *PersonMutation {
	return _c.mutation
}

// Save creates the Person in the database.
func (_c *PersonCreate) Save(ctx context.Context) (*Person, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonCreate) SaveX(ctx context.Context) *Person {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PersonCreate) defaults() {
	if _, ok := _c.mutation.Version(); !ok {
		v := person.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.FirstName(); !ok {
		v := person.DefaultFirstName
		_c.mutation.SetFirstName(v)
	}
	if _, ok := _c.mutation.LastName(); !ok {
		v := person.DefaultLastName
		_c.mutation.SetLastName(v)
	}
	if _, ok := _c.mutation.IdentityStatus(); !ok {
		v := person.DefaultIdentityStatus
		_c.mutation.SetIdentityStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := person.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := person.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := person.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Person.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := person.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Person.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "Person.organization_id"`)}
	}
	if _, ok := _c.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Person.first_name"`)}
	}
	if _, ok := _c.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Person.last_name"`)}
	}
	if _, ok := _c.mutation.IdentityStatus(); !ok {
		return &ValidationError{Name: "identity_status", err: errors.New(`ent: missing required field "Person.identity_status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Person.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Person.updated_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "Person.organization"`)}
	}
	return nil
}

func (_c *PersonCreate) sqlSave(ctx context.Context) (*Person, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonCreate) createSpec() (*Person, *sqlgraph.CreateSpec) {
	var (
		_node = &Person{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(person.Table, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(person.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(person.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(person.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := _c.mutation.IdentityStatus(); ok {
		_spec.SetField(person.FieldIdentityStatus, field.TypeString, value)
		_node.IdentityStatus = value
	}
	if value, ok := _c.mutation.MergedIntoPersonID(); ok {
		_spec.SetField(person.FieldMergedIntoPersonID, field.TypeUUID, value)
		_node.MergedIntoPersonID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(person.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(person.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   person.OrganizationTable,
			Columns: []string{person.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContactPointsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.ContactPointsTable,
			Columns: []string{person.ContactPointsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contactpoint.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AffiliationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.AffiliationsTable,
			Columns: []string{person.AffiliationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(churchaffiliation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.AccountsTable,
			Columns: []string{person.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.AssignmentsTable,
			Columns: []string{person.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PersonCreateBulk is the builder for creating many Person entities in bulk.
type PersonCreateBulk struct {
	config
	err      error
	builders []*PersonCreate
}

// Save creates the Person entities in the database.
func (_c *PersonCreateBulk) Save(ctx context.Context) ([]*Person, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Person, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonCreateBulk) SaveX(ctx context.Context) []*Person {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
