// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/v2/ent/assignment"
	"github.com/hofchurchng/church-backend/internal/v2/ent/capability"
	"github.com/hofchurchng/church-backend/internal/v2/ent/delegation"
	"github.com/hofchurchng/church-backend/internal/v2/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/v2/ent/scopedgrant"
)

// ScopedGrantQuery is the builder for querying ScopedGrant entities.
type ScopedGrantQuery struct {
	config
	ctx             *QueryContext
	order           []scopedgrant.OrderOption
	inters          []Interceptor
	predicates      []predicate.ScopedGrant
	withAssignment  *AssignmentQuery
	withCapability  *CapabilityQuery
	withDelegations *DelegationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScopedGrantQuery builder.
func (_q *ScopedGrantQuery) Where(ps ...predicate.ScopedGrant) *ScopedGrantQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ScopedGrantQuery) Limit(limit int) *ScopedGrantQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ScopedGrantQuery) Offset(offset int) *ScopedGrantQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ScopedGrantQuery) Unique(unique bool) *ScopedGrantQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ScopedGrantQuery) Order(o ...scopedgrant.OrderOption) *ScopedGrantQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAssignment chains the current query on the "assignment" edge.
func (_q *ScopedGrantQuery) QueryAssignment() *AssignmentQuery {
	query := (&AssignmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scopedgrant.Table, scopedgrant.FieldID, selector),
			sqlgraph.To(assignment.Table, assignment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scopedgrant.AssignmentTable, scopedgrant.AssignmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCapability chains the current query on the "capability" edge.
func (_q *ScopedGrantQuery) QueryCapability() *CapabilityQuery {
	query := (&CapabilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scopedgrant.Table, scopedgrant.FieldID, selector),
			sqlgraph.To(capability.Table, capability.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scopedgrant.CapabilityTable, scopedgrant.CapabilityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDelegations chains the current query on the "delegations" edge.
func (_q *ScopedGrantQuery) QueryDelegations() *DelegationQuery {
	query := (&DelegationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scopedgrant.Table, scopedgrant.FieldID, selector),
			sqlgraph.To(delegation.Table, delegation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, scopedgrant.DelegationsTable, scopedgrant.DelegationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ScopedGrant entity from the query.
// Returns a *NotFoundError when no ScopedGrant was found.
func (_q *ScopedGrantQuery) First(ctx context.Context) (*ScopedGrant, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scopedgrant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ScopedGrantQuery) FirstX(ctx context.Context) *ScopedGrant {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScopedGrant ID from the query.
// Returns a *NotFoundError when no ScopedGrant ID was found.
func (_q *ScopedGrantQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scopedgrant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ScopedGrantQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScopedGrant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScopedGrant entity is found.
// Returns a *NotFoundError when no ScopedGrant entities are found.
func (_q *ScopedGrantQuery) Only(ctx context.Context) (*ScopedGrant, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scopedgrant.Label}
	default:
		return nil, &NotSingularError{scopedgrant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ScopedGrantQuery) OnlyX(ctx context.Context) *ScopedGrant {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScopedGrant ID in the query.
// Returns a *NotSingularError when more than one ScopedGrant ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ScopedGrantQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scopedgrant.Label}
	default:
		err = &NotSingularError{scopedgrant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ScopedGrantQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScopedGrants.
func (_q *ScopedGrantQuery) All(ctx context.Context) ([]*ScopedGrant, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScopedGrant, *ScopedGrantQuery]()
	return withInterceptors[[]*ScopedGrant](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ScopedGrantQuery) AllX(ctx context.Context) []*ScopedGrant {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScopedGrant IDs.
func (_q *ScopedGrantQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(scopedgrant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ScopedGrantQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ScopedGrantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ScopedGrantQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ScopedGrantQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ScopedGrantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ScopedGrantQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScopedGrantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ScopedGrantQuery) Clone() *ScopedGrantQuery {
	if _q == nil {
		return nil
	}
	return &ScopedGrantQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]scopedgrant.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.ScopedGrant{}, _q.predicates...),
		withAssignment:  _q.withAssignment.Clone(),
		withCapability:  _q.withCapability.Clone(),
		withDelegations: _q.withDelegations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAssignment tells the query-builder to eager-load the nodes that are connected to
// the "assignment" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScopedGrantQuery) WithAssignment(opts ...func(*AssignmentQuery)) *ScopedGrantQuery {
	query := (&AssignmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAssignment = query
	return _q
}

// WithCapability tells the query-builder to eager-load the nodes that are connected to
// the "capability" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScopedGrantQuery) WithCapability(opts ...func(*CapabilityQuery)) *ScopedGrantQuery {
	query := (&CapabilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCapability = query
	return _q
}

// WithDelegations tells the query-builder to eager-load the nodes that are connected to
// the "delegations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScopedGrantQuery) WithDelegations(opts ...func(*DelegationQuery)) *ScopedGrantQuery {
	query := (&DelegationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDelegations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Version int `json:"version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScopedGrant.Query().
//		GroupBy(scopedgrant.FieldVersion).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ScopedGrantQuery) GroupBy(field string, fields ...string) *ScopedGrantGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScopedGrantGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = scopedgrant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Version int `json:"version,omitempty"`
//	}
//
//	client.ScopedGrant.Query().
//		Select(scopedgrant.FieldVersion).
//		Scan(ctx, &v)
func (_q *ScopedGrantQuery) Select(fields ...string) *ScopedGrantSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ScopedGrantSelect{ScopedGrantQuery: _q}
	sbuild.label = scopedgrant.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScopedGrantSelect configured with the given aggregations.
func (_q *ScopedGrantQuery) Aggregate(fns ...AggregateFunc) *ScopedGrantSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ScopedGrantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !scopedgrant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ScopedGrantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScopedGrant, error) {
	var (
		nodes       = []*ScopedGrant{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withAssignment != nil,
			_q.withCapability != nil,
			_q.withDelegations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScopedGrant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScopedGrant{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAssignment; query != nil {
		if err := _q.loadAssignment(ctx, query, nodes, nil,
			func(n *ScopedGrant, e *Assignment) { n.Edges.Assignment = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCapability; query != nil {
		if err := _q.loadCapability(ctx, query, nodes, nil,
			func(n *ScopedGrant, e *Capability) { n.Edges.Capability = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDelegations; query != nil {
		if err := _q.loadDelegations(ctx, query, nodes,
			func(n *ScopedGrant) { n.Edges.Delegations = []*Delegation{} },
			func(n *ScopedGrant, e *Delegation) { n.Edges.Delegations = append(n.Edges.Delegations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ScopedGrantQuery) loadAssignment(ctx context.Context, query *AssignmentQuery, nodes []*ScopedGrant, init func(*ScopedGrant), assign func(*ScopedGrant, *Assignment)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ScopedGrant)
	for i := range nodes {
		fk := nodes[i].AssignmentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(assignment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "assignment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ScopedGrantQuery) loadCapability(ctx context.Context, query *CapabilityQuery, nodes []*ScopedGrant, init func(*ScopedGrant), assign func(*ScopedGrant, *Capability)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ScopedGrant)
	for i := range nodes {
		fk := nodes[i].CapabilityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(capability.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "capability_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ScopedGrantQuery) loadDelegations(ctx context.Context, query *DelegationQuery, nodes []*ScopedGrant, init func(*ScopedGrant), assign func(*ScopedGrant, *Delegation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ScopedGrant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(delegation.FieldParentGrantID)
	}
	query.Where(predicate.Delegation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(scopedgrant.DelegationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentGrantID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_grant_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ScopedGrantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ScopedGrantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scopedgrant.Table, scopedgrant.Columns, sqlgraph.NewFieldSpec(scopedgrant.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scopedgrant.FieldID)
		for i := range fields {
			if fields[i] != scopedgrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAssignment != nil {
			_spec.Node.AddColumnOnce(scopedgrant.FieldAssignmentID)
		}
		if _q.withCapability != nil {
			_spec.Node.AddColumnOnce(scopedgrant.FieldCapabilityID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ScopedGrantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(scopedgrant.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = scopedgrant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScopedGrantGroupBy is the group-by builder for ScopedGrant entities.
type ScopedGrantGroupBy struct {
	selector
	build *ScopedGrantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ScopedGrantGroupBy) Aggregate(fns ...AggregateFunc) *ScopedGrantGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ScopedGrantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScopedGrantQuery, *ScopedGrantGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ScopedGrantGroupBy) sqlScan(ctx context.Context, root *ScopedGrantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScopedGrantSelect is the builder for selecting fields of ScopedGrant entities.
type ScopedGrantSelect struct {
	*ScopedGrantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ScopedGrantSelect) Aggregate(fns ...AggregateFunc) *ScopedGrantSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ScopedGrantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScopedGrantQuery, *ScopedGrantSelect](ctx, _s.ScopedGrantQuery, _s, _s.inters, v)
}

func (_s *ScopedGrantSelect) sqlScan(ctx context.Context, root *ScopedGrantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
