// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/v2/ent/assignment"
	"github.com/hofchurchng/church-backend/internal/v2/ent/capability"
	"github.com/hofchurchng/church-backend/internal/v2/ent/scopedgrant"
)

// ScopedGrant is the model entity for the ScopedGrant schema.
type ScopedGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Delegable holds the value of the "delegable" field.
	Delegable bool `json:"delegable,omitempty"`
	// AssignmentID holds the value of the "assignment_id" field.
	AssignmentID uuid.UUID `json:"assignment_id,omitempty"`
	// CapabilityID holds the value of the "capability_id" field.
	CapabilityID uuid.UUID `json:"capability_id,omitempty"`
	// ScopeLevel holds the value of the "scope_level" field.
	ScopeLevel string `json:"scope_level,omitempty"`
	// ScopeResourceID holds the value of the "scope_resource_id" field.
	ScopeResourceID *uuid.UUID `json:"scope_resource_id,omitempty"`
	// SensitivityClass holds the value of the "sensitivity_class" field.
	SensitivityClass string `json:"sensitivity_class,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil *time.Time `json:"valid_until,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScopedGrantQuery when eager-loading is set.
	Edges        ScopedGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScopedGrantEdges holds the relations/edges for other nodes in the graph.
type ScopedGrantEdges struct {
	// Assignment holds the value of the assignment edge.
	Assignment *Assignment `json:"assignment,omitempty"`
	// Capability holds the value of the capability edge.
	Capability *Capability `json:"capability,omitempty"`
	// Delegations holds the value of the delegations edge.
	Delegations []*Delegation `json:"delegations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AssignmentOrErr returns the Assignment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScopedGrantEdges) AssignmentOrErr() (*Assignment, error) {
	if e.Assignment != nil {
		return e.Assignment, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: assignment.Label}
	}
	return nil, &NotLoadedError{edge: "assignment"}
}

// CapabilityOrErr returns the Capability value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScopedGrantEdges) CapabilityOrErr() (*Capability, error) {
	if e.Capability != nil {
		return e.Capability, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: capability.Label}
	}
	return nil, &NotLoadedError{edge: "capability"}
}

// DelegationsOrErr returns the Delegations value or an error if the edge
// was not loaded in eager-loading.
func (e ScopedGrantEdges) DelegationsOrErr() ([]*Delegation, error) {
	if e.loadedTypes[2] {
		return e.Delegations, nil
	}
	return nil, &NotLoadedError{edge: "delegations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScopedGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scopedgrant.FieldScopeResourceID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case scopedgrant.FieldDelegable:
			values[i] = new(sql.NullBool)
		case scopedgrant.FieldVersion:
			values[i] = new(sql.NullInt64)
		case scopedgrant.FieldScopeLevel, scopedgrant.FieldSensitivityClass:
			values[i] = new(sql.NullString)
		case scopedgrant.FieldCreatedAt, scopedgrant.FieldUpdatedAt, scopedgrant.FieldRevokedAt, scopedgrant.FieldValidFrom, scopedgrant.FieldValidUntil:
			values[i] = new(sql.NullTime)
		case scopedgrant.FieldID, scopedgrant.FieldAssignmentID, scopedgrant.FieldCapabilityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScopedGrant fields.
func (_m *ScopedGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scopedgrant.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case scopedgrant.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case scopedgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case scopedgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case scopedgrant.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case scopedgrant.FieldDelegable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field delegable", values[i])
			} else if value.Valid {
				_m.Delegable = value.Bool
			}
		case scopedgrant.FieldAssignmentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field assignment_id", values[i])
			} else if value != nil {
				_m.AssignmentID = *value
			}
		case scopedgrant.FieldCapabilityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field capability_id", values[i])
			} else if value != nil {
				_m.CapabilityID = *value
			}
		case scopedgrant.FieldScopeLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_level", values[i])
			} else if value.Valid {
				_m.ScopeLevel = value.String
			}
		case scopedgrant.FieldScopeResourceID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field scope_resource_id", values[i])
			} else if value.Valid {
				_m.ScopeResourceID = new(uuid.UUID)
				*_m.ScopeResourceID = *value.S.(*uuid.UUID)
			}
		case scopedgrant.FieldSensitivityClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sensitivity_class", values[i])
			} else if value.Valid {
				_m.SensitivityClass = value.String
			}
		case scopedgrant.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case scopedgrant.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				_m.ValidUntil = new(time.Time)
				*_m.ValidUntil = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScopedGrant.
// This includes values selected through modifiers, order, etc.
func (_m *ScopedGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAssignment queries the "assignment" edge of the ScopedGrant entity.
func (_m *ScopedGrant) QueryAssignment() *AssignmentQuery {
	return NewScopedGrantClient(_m.config).QueryAssignment(_m)
}

// QueryCapability queries the "capability" edge of the ScopedGrant entity.
func (_m *ScopedGrant) QueryCapability() *CapabilityQuery {
	return NewScopedGrantClient(_m.config).QueryCapability(_m)
}

// QueryDelegations queries the "delegations" edge of the ScopedGrant entity.
func (_m *ScopedGrant) QueryDelegations() *DelegationQuery {
	return NewScopedGrantClient(_m.config).QueryDelegations(_m)
}

// Update returns a builder for updating this ScopedGrant.
// Note that you need to call ScopedGrant.Unwrap() before calling this method if this ScopedGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScopedGrant) Update() *ScopedGrantUpdateOne {
	return NewScopedGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScopedGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScopedGrant) Unwrap() *ScopedGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScopedGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScopedGrant) String() string {
	var builder strings.Builder
	builder.WriteString("ScopedGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("delegable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Delegable))
	builder.WriteString(", ")
	builder.WriteString("assignment_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssignmentID))
	builder.WriteString(", ")
	builder.WriteString("capability_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CapabilityID))
	builder.WriteString(", ")
	builder.WriteString("scope_level=")
	builder.WriteString(_m.ScopeLevel)
	builder.WriteString(", ")
	if v := _m.ScopeResourceID; v != nil {
		builder.WriteString("scope_resource_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("sensitivity_class=")
	builder.WriteString(_m.SensitivityClass)
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidUntil; v != nil {
		builder.WriteString("valid_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ScopedGrants is a parsable slice of ScopedGrant.
type ScopedGrants []*ScopedGrant
