// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/v2/ent/branch"
	"github.com/hofchurchng/church-backend/internal/v2/ent/predicate"
	"github.com/hofchurchng/church-backend/internal/v2/ent/sector"
)

// SectorUpdate is the builder for updating Sector entities.
type SectorUpdate struct {
	config
	hooks    []Hook
	mutation *SectorMutation
}

// Where appends a list predicates to the SectorUpdate builder.
func (_u *SectorUpdate) Where(ps ...predicate.Sector) *SectorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *SectorUpdate) SetVersion(v int) *SectorUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableVersion(v *int) *SectorUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SectorUpdate) AddVersion(v int) *SectorUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *SectorUpdate) SetOrganizationID(v uuid.UUID) *SectorUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableOrganizationID(v *uuid.UUID) *SectorUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetBranchID sets the "branch_id" field.
func (_u *SectorUpdate) SetBranchID(v uuid.UUID) *SectorUpdate {
	_u.mutation.SetBranchID(v)
	return _u
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableBranchID(v *uuid.UUID) *SectorUpdate {
	if v != nil {
		_u.SetBranchID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SectorUpdate) SetName(v string) *SectorUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableName(v *string) *SectorUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SectorUpdate) SetStatus(v string) *SectorUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableStatus(v *string) *SectorUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SectorUpdate) SetCreatedAt(v time.Time) *SectorUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SectorUpdate) SetNillableCreatedAt(v *time.Time) *SectorUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SectorUpdate) SetUpdatedAt(v time.Time) *SectorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_u *SectorUpdate) SetBranch(v *Branch) *SectorUpdate {
	return _u.SetBranchID(v.ID)
}

// Mutation returns the SectorMutation object of the builder.
func (_u *SectorUpdate) Mutation() *SectorMutation {
	return _u.mutation
}

// ClearBranch clears the "branch" edge to the Branch entity.
func (_u *SectorUpdate) ClearBranch() *SectorUpdate {
	_u.mutation.ClearBranch()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SectorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SectorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SectorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sector.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectorUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := sector.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Sector.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sector.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sector.name": %w`, err)}
		}
	}
	if _u.mutation.BranchCleared() && len(_u.mutation.BranchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sector.branch"`)
	}
	return nil
}

func (_u *SectorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sector.Table, sector.Columns, sqlgraph.NewFieldSpec(sector.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(sector.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(sector.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(sector.FieldOrganizationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sector.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sector.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sector.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sector.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BranchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.BranchTable,
			Columns: []string{sector.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.BranchTable,
			Columns: []string{sector.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SectorUpdateOne is the builder for updating a single Sector entity.
type SectorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SectorMutation
}

// SetVersion sets the "version" field.
func (_u *SectorUpdateOne) SetVersion(v int) *SectorUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableVersion(v *int) *SectorUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SectorUpdateOne) AddVersion(v int) *SectorUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *SectorUpdateOne) SetOrganizationID(v uuid.UUID) *SectorUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *SectorUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetBranchID sets the "branch_id" field.
func (_u *SectorUpdateOne) SetBranchID(v uuid.UUID) *SectorUpdateOne {
	_u.mutation.SetBranchID(v)
	return _u
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableBranchID(v *uuid.UUID) *SectorUpdateOne {
	if v != nil {
		_u.SetBranchID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SectorUpdateOne) SetName(v string) *SectorUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableName(v *string) *SectorUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SectorUpdateOne) SetStatus(v string) *SectorUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableStatus(v *string) *SectorUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SectorUpdateOne) SetCreatedAt(v time.Time) *SectorUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SectorUpdateOne) SetNillableCreatedAt(v *time.Time) *SectorUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SectorUpdateOne) SetUpdatedAt(v time.Time) *SectorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_u *SectorUpdateOne) SetBranch(v *Branch) *SectorUpdateOne {
	return _u.SetBranchID(v.ID)
}

// Mutation returns the SectorMutation object of the builder.
func (_u *SectorUpdateOne) Mutation() *SectorMutation {
	return _u.mutation
}

// ClearBranch clears the "branch" edge to the Branch entity.
func (_u *SectorUpdateOne) ClearBranch() *SectorUpdateOne {
	_u.mutation.ClearBranch()
	return _u
}

// Where appends a list predicates to the SectorUpdate builder.
func (_u *SectorUpdateOne) Where(ps ...predicate.Sector) *SectorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SectorUpdateOne) Select(field string, fields ...string) *SectorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sector entity.
func (_u *SectorUpdateOne) Save(ctx context.Context) (*Sector, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SectorUpdateOne) SaveX(ctx context.Context) *Sector {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SectorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SectorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SectorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sector.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SectorUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := sector.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Sector.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sector.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sector.name": %w`, err)}
		}
	}
	if _u.mutation.BranchCleared() && len(_u.mutation.BranchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sector.branch"`)
	}
	return nil
}

func (_u *SectorUpdateOne) sqlSave(ctx context.Context) (_node *Sector, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sector.Table, sector.Columns, sqlgraph.NewFieldSpec(sector.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sector.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sector.FieldID)
		for _, f := range fields {
			if !sector.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(sector.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(sector.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(sector.FieldOrganizationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sector.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sector.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(sector.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sector.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BranchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.BranchTable,
			Columns: []string{sector.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sector.BranchTable,
			Columns: []string{sector.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sector{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
