// Code generated by ent, DO NOT EDIT.

package consumerreceipt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hofchurchng/church-backend/internal/v2/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLTE(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldVersion, v))
}

// ConsumerName applies equality check predicate on the "consumer_name" field. It's identical to ConsumerNameEQ.
func ConsumerName(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldConsumerName, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldEventID, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldProcessedAt, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLTE(FieldVersion, v))
}

// ConsumerNameEQ applies the EQ predicate on the "consumer_name" field.
func ConsumerNameEQ(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldConsumerName, v))
}

// ConsumerNameNEQ applies the NEQ predicate on the "consumer_name" field.
func ConsumerNameNEQ(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNEQ(FieldConsumerName, v))
}

// ConsumerNameIn applies the In predicate on the "consumer_name" field.
func ConsumerNameIn(vs ...string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldIn(FieldConsumerName, vs...))
}

// ConsumerNameNotIn applies the NotIn predicate on the "consumer_name" field.
func ConsumerNameNotIn(vs ...string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNotIn(FieldConsumerName, vs...))
}

// ConsumerNameGT applies the GT predicate on the "consumer_name" field.
func ConsumerNameGT(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGT(FieldConsumerName, v))
}

// ConsumerNameGTE applies the GTE predicate on the "consumer_name" field.
func ConsumerNameGTE(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGTE(FieldConsumerName, v))
}

// ConsumerNameLT applies the LT predicate on the "consumer_name" field.
func ConsumerNameLT(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLT(FieldConsumerName, v))
}

// ConsumerNameLTE applies the LTE predicate on the "consumer_name" field.
func ConsumerNameLTE(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLTE(FieldConsumerName, v))
}

// ConsumerNameContains applies the Contains predicate on the "consumer_name" field.
func ConsumerNameContains(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldContains(FieldConsumerName, v))
}

// ConsumerNameHasPrefix applies the HasPrefix predicate on the "consumer_name" field.
func ConsumerNameHasPrefix(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldHasPrefix(FieldConsumerName, v))
}

// ConsumerNameHasSuffix applies the HasSuffix predicate on the "consumer_name" field.
func ConsumerNameHasSuffix(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldHasSuffix(FieldConsumerName, v))
}

// ConsumerNameEqualFold applies the EqualFold predicate on the "consumer_name" field.
func ConsumerNameEqualFold(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEqualFold(FieldConsumerName, v))
}

// ConsumerNameContainsFold applies the ContainsFold predicate on the "consumer_name" field.
func ConsumerNameContainsFold(v string) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldContainsFold(FieldConsumerName, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v uuid.UUID) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLTE(FieldEventID, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.FieldLTE(FieldProcessedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConsumerReceipt) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConsumerReceipt) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConsumerReceipt) predicate.ConsumerReceipt {
	return predicate.ConsumerReceipt(sql.NotPredicates(p))
}
