// Code generated by ent, DO NOT EDIT.

package continuousassessment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the continuousassessment type in the database.
	Label = "continuous_assessment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEnrollmentID holds the string denoting the enrollment_id field in the database.
	FieldEnrollmentID = "enrollment_id"
	// FieldAssignmentScore holds the string denoting the assignment_score field in the database.
	FieldAssignmentScore = "assignment_score"
	// FieldVerbalAssessmentScore holds the string denoting the verbal_assessment_score field in the database.
	FieldVerbalAssessmentScore = "verbal_assessment_score"
	// FieldParticipationScore holds the string denoting the participation_score field in the database.
	FieldParticipationScore = "participation_score"
	// FieldDisciplersReportScore holds the string denoting the disciplers_report_score field in the database.
	FieldDisciplersReportScore = "disciplers_report_score"
	// FieldProofOfNoteScore holds the string denoting the proof_of_note_score field in the database.
	FieldProofOfNoteScore = "proof_of_note_score"
	// FieldAttendanceScore holds the string denoting the attendance_score field in the database.
	FieldAttendanceScore = "attendance_score"
	// FieldTotalScore holds the string denoting the total_score field in the database.
	FieldTotalScore = "total_score"
	// FieldDisciplerDevotionRating holds the string denoting the discipler_devotion_rating field in the database.
	FieldDisciplerDevotionRating = "discipler_devotion_rating"
	// FieldDisciplerEvangelismRating holds the string denoting the discipler_evangelism_rating field in the database.
	FieldDisciplerEvangelismRating = "discipler_evangelism_rating"
	// FieldMakeupCompleted holds the string denoting the makeup_completed field in the database.
	FieldMakeupCompleted = "makeup_completed"
	// FieldGradedByUserID holds the string denoting the graded_by_user_id field in the database.
	FieldGradedByUserID = "graded_by_user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the continuousassessment in the database.
	Table = "continuous_assessments"
)

// Columns holds all SQL columns for continuousassessment fields.
var Columns = []string{
	FieldID,
	FieldEnrollmentID,
	FieldAssignmentScore,
	FieldVerbalAssessmentScore,
	FieldParticipationScore,
	FieldDisciplersReportScore,
	FieldProofOfNoteScore,
	FieldAttendanceScore,
	FieldTotalScore,
	FieldDisciplerDevotionRating,
	FieldDisciplerEvangelismRating,
	FieldMakeupCompleted,
	FieldGradedByUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAssignmentScore holds the default value on creation for the "assignment_score" field.
	DefaultAssignmentScore float64
	// DefaultVerbalAssessmentScore holds the default value on creation for the "verbal_assessment_score" field.
	DefaultVerbalAssessmentScore float64
	// DefaultParticipationScore holds the default value on creation for the "participation_score" field.
	DefaultParticipationScore float64
	// DefaultDisciplersReportScore holds the default value on creation for the "disciplers_report_score" field.
	DefaultDisciplersReportScore float64
	// DefaultProofOfNoteScore holds the default value on creation for the "proof_of_note_score" field.
	DefaultProofOfNoteScore float64
	// DefaultAttendanceScore holds the default value on creation for the "attendance_score" field.
	DefaultAttendanceScore float64
	// DefaultTotalScore holds the default value on creation for the "total_score" field.
	DefaultTotalScore float64
	// DefaultDisciplerDevotionRating holds the default value on creation for the "discipler_devotion_rating" field.
	DefaultDisciplerDevotionRating int
	// DefaultDisciplerEvangelismRating holds the default value on creation for the "discipler_evangelism_rating" field.
	DefaultDisciplerEvangelismRating int
	// DefaultMakeupCompleted holds the default value on creation for the "makeup_completed" field.
	DefaultMakeupCompleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ContinuousAssessment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEnrollmentID orders the results by the enrollment_id field.
func ByEnrollmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnrollmentID, opts...).ToFunc()
}

// ByAssignmentScore orders the results by the assignment_score field.
func ByAssignmentScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignmentScore, opts...).ToFunc()
}

// ByVerbalAssessmentScore orders the results by the verbal_assessment_score field.
func ByVerbalAssessmentScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerbalAssessmentScore, opts...).ToFunc()
}

// ByParticipationScore orders the results by the participation_score field.
func ByParticipationScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParticipationScore, opts...).ToFunc()
}

// ByDisciplersReportScore orders the results by the disciplers_report_score field.
func ByDisciplersReportScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisciplersReportScore, opts...).ToFunc()
}

// ByProofOfNoteScore orders the results by the proof_of_note_score field.
func ByProofOfNoteScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProofOfNoteScore, opts...).ToFunc()
}

// ByAttendanceScore orders the results by the attendance_score field.
func ByAttendanceScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttendanceScore, opts...).ToFunc()
}

// ByTotalScore orders the results by the total_score field.
func ByTotalScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalScore, opts...).ToFunc()
}

// ByDisciplerDevotionRating orders the results by the discipler_devotion_rating field.
func ByDisciplerDevotionRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisciplerDevotionRating, opts...).ToFunc()
}

// ByDisciplerEvangelismRating orders the results by the discipler_evangelism_rating field.
func ByDisciplerEvangelismRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisciplerEvangelismRating, opts...).ToFunc()
}

// ByMakeupCompleted orders the results by the makeup_completed field.
func ByMakeupCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMakeupCompleted, opts...).ToFunc()
}

// ByGradedByUserID orders the results by the graded_by_user_id field.
func ByGradedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGradedByUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
